insert into CMDS_M_PRAC values('01','01:内科');
insert into CMDS_M_PRAC values('02','02:精神科');
insert into CMDS_M_PRAC values('09','09:小児科');
insert into CMDS_M_PRAC values('10','10:外科');
insert into CMDS_M_PRAC values('19','19:皮膚科');
insert into CMDS_M_PRAC values('20','20:ひ尿器科');
insert into CMDS_M_PRAC values('23','23:産婦人科（ 産科又は婦人科）');
insert into CMDS_M_PRAC values('26','26:眼科');
insert into CMDS_M_PRAC values('27','27:耳鼻いんこう科');
insert into CMDS_M_PRAC values('30','30:放射線科（ 放射線診断科又は放射線治療科）');
insert into CMDS_M_PRAC values('31','31:麻酔科');
insert into CMDS_M_PRAC values('34','34:アレルギー科');
insert into CMDS_M_PRAC values('35','35:リウマチ科');
insert into CMDS_M_PRAC values('36','36:リハビリテーション科');
insert into CMDS_M_PRAC values('37','37:病理診断科');
insert into CMDS_M_PRAC values('38','38:臨床検査科');
insert into CMDS_M_PRAC values('39','39:救急科');
insert into CMDS_M_PRAC values('03','03:神経科');
insert into CMDS_M_PRAC values('04','04:神経内科');
insert into CMDS_M_PRAC values('05','05:呼吸器科');
insert into CMDS_M_PRAC values('06','06:消化器科');
insert into CMDS_M_PRAC values('07','07:胃腸科');
insert into CMDS_M_PRAC values('08','08:循環器科');
insert into CMDS_M_PRAC values('11','11:整形外科');
insert into CMDS_M_PRAC values('12','12:形成外科');
insert into CMDS_M_PRAC values('13','13:美容外科');
insert into CMDS_M_PRAC values('14','14:脳神経外科');
insert into CMDS_M_PRAC values('15','15:呼吸器外科');
insert into CMDS_M_PRAC values('16','16:心臓血管外科');
insert into CMDS_M_PRAC values('17','17:小児外科');
insert into CMDS_M_PRAC values('18','18:皮膚ひ尿器科');
insert into CMDS_M_PRAC values('21','21:性病科');
insert into CMDS_M_PRAC values('22','22:こう門科');
insert into CMDS_M_PRAC values('24','24:産科');
insert into CMDS_M_PRAC values('25','25:婦人科');
insert into CMDS_M_PRAC values('28','28:気管食道科');
insert into CMDS_M_PRAC values('33','33:心療内科');
commit;
