insert into CMDS_M_RCP_IMPTT_NOTI values('01','公');
insert into CMDS_M_RCP_IMPTT_NOTI values('02','長');
insert into CMDS_M_RCP_IMPTT_NOTI values('03','長処');
insert into CMDS_M_RCP_IMPTT_NOTI values('04','後保');
insert into CMDS_M_RCP_IMPTT_NOTI values('07','老併');
insert into CMDS_M_RCP_IMPTT_NOTI values('08','老健');
insert into CMDS_M_RCP_IMPTT_NOTI values('09','施');
insert into CMDS_M_RCP_IMPTT_NOTI values('10','第三');
insert into CMDS_M_RCP_IMPTT_NOTI values('11','薬治');
insert into CMDS_M_RCP_IMPTT_NOTI values('12','器治');
insert into CMDS_M_RCP_IMPTT_NOTI values('13','先進');
insert into CMDS_M_RCP_IMPTT_NOTI values('14','制超');
insert into CMDS_M_RCP_IMPTT_NOTI values('16','長２');
insert into CMDS_M_RCP_IMPTT_NOTI values('17','上位');
insert into CMDS_M_RCP_IMPTT_NOTI values('18','一般');
insert into CMDS_M_RCP_IMPTT_NOTI values('19','低所');
insert into CMDS_M_RCP_IMPTT_NOTI values('20','二割');
insert into CMDS_M_RCP_IMPTT_NOTI values('21','高半');
insert into CMDS_M_RCP_IMPTT_NOTI values('22','多上');
insert into CMDS_M_RCP_IMPTT_NOTI values('23','多一');
insert into CMDS_M_RCP_IMPTT_NOTI values('24','多低');
insert into CMDS_M_RCP_IMPTT_NOTI values('25','出産');
insert into CMDS_M_RCP_IMPTT_NOTI values('26','区 ア');
insert into CMDS_M_RCP_IMPTT_NOTI values('27','区 イ');
insert into CMDS_M_RCP_IMPTT_NOTI values('28','区 ウ');
insert into CMDS_M_RCP_IMPTT_NOTI values('29','区 エ');
insert into CMDS_M_RCP_IMPTT_NOTI values('30','区 オ');
insert into CMDS_M_RCP_IMPTT_NOTI values('31','多 ア');
insert into CMDS_M_RCP_IMPTT_NOTI values('32','多 イ');
insert into CMDS_M_RCP_IMPTT_NOTI values('33','多 ウ');
insert into CMDS_M_RCP_IMPTT_NOTI values('34','多 エ');
insert into CMDS_M_RCP_IMPTT_NOTI values('35','多 オ');
insert into CMDS_M_RCP_IMPTT_NOTI values('36','加 治');
insert into CMDS_M_RCP_IMPTT_NOTI values('40','５０／１００');
commit;
