insert into CMDS_M_SEX values('001','男性');
insert into CMDS_M_SEX values('002','女性');
insert into CMDS_M_SEX values('003','小児');
insert into CMDS_M_SEX values('004','老人');
insert into CMDS_M_SEX values('005','周産期');
insert into CMDS_M_SEX values('006','新生児');
insert into CMDS_M_SEX values('007','児童');
insert into CMDS_M_SEX values('008','思春期');
insert into CMDS_M_SEX values('009','老年');
insert into CMDS_M_SEX values('010','高齢者');
commit;
