CREATE VIEW CMDV_T_RCP_MED_IR AS
  SELECT
    IR.SEQ1_NO
 ,  IR.SEQ2_NO
 ,  IR.VLD_FLG
 ,  IR.REC_IDENT_INFO
 ,  IR.EXAM_PAY_INST
 ,  IR.TDFK
 ,  IR.SCORE_LIST
 ,  IR.MEDI_INST_CD
 ,  IR.PRAC_DEPT_CD
 ,  IR.REQ_YM
 ,  IR.MLT_VOL_IDENT_INFO
 ,  M_MIC.VCI_HSPTL_DIV
 ,  IR.PRAC_YM
 ,  IR.INPUT_YM
  FROM TNDS_T_RCP_MED_IR IR
  LEFT OUTER JOIN 
    (
     select MIC_TDFK_NO,MIC_SCORE_LIST_NO,MIC_CITY_AREA_NO,MIC_MIDI_INST_NO,MIC_VFCT_NO,VCI_HSPTL_DIV 
     from TNDS_M_MIC M_MIC where MST_GEN = 
     	(
     	select MIC_MST_GEN
		from TNDS_T_MSTLINK
		where APPL_YM_W = (select MAX(APPL_YM_W) from TNDS_T_MSTLINK)
		)) M_MIC
   ON  ( IR.TDFK = M_MIC.MIC_TDFK_NO
   AND IR.SCORE_LIST = M_MIC.MIC_SCORE_LIST_NO
   AND SUBSTR( IR.MEDI_INST_CD_ORG , 1 , 2 ) = M_MIC.MIC_CITY_AREA_NO
   AND SUBSTR( IR.MEDI_INST_CD_ORG , 3 , 4 ) = M_MIC.MIC_MIDI_INST_NO
   AND SUBSTR( IR.MEDI_INST_CD_ORG , 7 , 1 ) = M_MIC.MIC_VFCT_NO )
  WHERE
   IR.KO_FLG IN (0,2)
WITH READ ONLY
;
