CREATE VIEW CMDV_T_RCP_MED_SY AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  SKWD_NAME_CD
 ,  PRAC_STR_YMD
 ,  OUTCM_DIV
 ,  MODIF_CD
 ,  SSPCT_DSS_FLG
 ,  MAIN_SKWD
 ,  MAIN_SKWD_DECIS_FLG
 ,  MAIN_SKWD_DECIS_ERR
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_MED_SY
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
