CREATE VIEW CMDV_T_RCP_MED_TS AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  PRAC_TRUE_DAYS
 ,  TOTAL_SCORE
 ,  TIMES
 ,  TOTAL_PRICE
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_MED_TS
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
