CREATE VIEW CMDV_T_RCP_DPC_MN AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  RCP_MNG_NO
 ,  INSU_MEDI_INST_ADDR
 ,  RESERVE_01
 ,  RESERVE_02
 ,  RESERVE_03
 ,  RESERVE_04
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DPC_MN
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
