CREATE VIEW CMDV_T_RCP_DPC_RE AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  AGE
 ,  ID1
 ,  ID1N
 ,  ID2
 ,  RCP_NO
 ,  RCP_CLS
 ,  PRAC_YM
 ,  SEX_DIV
 ,  BIRTH_YM
 ,  PAY_RAT
 ,  HOSTZ_YMD
 ,  WARD_DIV
 ,  STAND_BURD_DIV
 ,  RCPT_IMPTT_NOTI
 ,  RESERVE_01
 ,  DISCNT_SCR_UNIT_PRICE
 ,  RESERVE_02
 ,  RESERVE_03
 ,  INDI_PRAC_DEPT
 ,  RCPT_GNRLZ_DIV
 ,  DETL_INFO_NUM
 ,  SRCH_NO
 ,  REC_CNDTN_SPEC_YM_INFO
 ,  REQ_INFO
 ,  PRAC1_NAME
 ,  PRAC1_BODY_PART
 ,  PRAC1_SEX
 ,  PRAC1_MEDI_TREAT
 ,  PRAC1_SPCFC_DISE
 ,  INPUT_YM
 ,  AGE_HIER_CD1
 ,  AGE_HIER_CD2
 ,  LAST_BIRTH_AGE
 ,  LAST_BIRTH_AGE_HIER_CD1
 ,  LAST_BIRTH_AGE_HIER_CD2
  FROM
    TNDS_T_RCP_DPC_RE
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
