CREATE VIEW CMDV_T_RCP_DPC_CO AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  PRAC_IDENT
 ,  BURD_DIV
 ,  CMT_CD
 ,  AFT_SPLMT_PRAC_IDENT
 ,  SERL_NO
 ,  SERS_ODR
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DPC_CO
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
