CREATE VIEW CMDV_T_RCP_DPC_BU AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  DIAG_GRP_CLS_NO
 ,  THIS_HOSTZ_YMD
 ,  THIS_DSCHG_YMD
 ,  DPC_OUTCM_DIV
 ,  CAUSE_DEATH
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DPC_BU
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
