CREATE VIEW CMDV_T_RCP_DPC_SB AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  SKWD_NAME_CD
 ,  MODIF_CD
 ,  SSPCT_DSS_FLG
 ,  ICD10_CD
 ,  SKWD_NAME_DIV
 ,  CAUSE_DEATH
 ,  MAIN_SKWD_DECIS_FLG
 ,  MAIN_SKWD_DECIS_ERR
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DPC_SB
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
