CREATE VIEW CMDV_T_RCP_DPC_KK AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  CHG_DEPT_YON
 ,  EXCPT_PUB_WARD_MOVE_YON
 ,  PLAN_EMGCY_HOSTZ_DIV
 ,  LAST_DSCHG_YMD
 ,  LAST_SAME_SKWD_HOSTZ_YON
 ,  HOSTZ_AGE
 ,  BIRTH_WT
 ,  JCS
 ,  RESERVE_01
 ,  BURN_IDX
 ,  SEVERITY
 ,  GAF
 ,  HOSTZ_MONTH_AGE
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DPC_KK
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
