CREATE VIEW CMDV_T_RCP_DPC_SK AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  PRAC_ACT_CD
 ,  DIV_NO
 ,  OPRTN_PLAN_YMD
 ,  RESERVE_01
 ,  PRAC_DIV_CD
 ,  PRAC_NAME
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DPC_SK
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
