CREATE VIEW CMDV_T_RCP_DPC_GA AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  PRAC_YM_GA
 ,  REQ_ADJST_DIV
 ,  STAY_OUT
 ,  DIAG_GRP_CLS_NO
 ,  NEXT_HOSTZ_PLAN_YON
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DPC_GA
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
