CREATE VIEW CMDV_T_RCP_DPC_HH AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  PRAC_YM_HH
 ,  REQ_ADJST_DIV
 ,  SELF_OTHER_INSU_DIV
 ,  BURD_DIV
 ,  HOSTZ_PRD_DIV
 ,  HOSTZ_PRD_DIV_SCORE
 ,  HOSTZ_PRD_DIV_DAYS
 ,  INCSN_SBTTL_SCORE
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DPC_HH
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
