CREATE VIEW CMDV_T_RCP_DPC_TI AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  ORGAN_DONAT_DIV
 ,  ORGAN_DONAT_MEDI_INST_DIV
 ,  TDFK
 ,  SCORE_LIST
 ,  MEDI_INST_CD
 ,  PRAC_DEPT_CD
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DPC_TI
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
