CREATE VIEW CMDV_T_RCP_DPC_TR AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  RCP_NO
 ,  DONOR_RCPT_CLS
 ,  PRAC_YM_TR
 ,  ID3
 ,  SEX_DIV
 ,  BIRTH_YM
 ,  NAME
 ,  HOSTZ_YMD
 ,  WARD_DIV
 ,  RESERVE_01
 ,  RCPT_IMPTT_NOTI
 ,  RESERVE_02
 ,  DISCNT_SCR_UNIT_PRICE
 ,  RESERVE_03
 ,  RESERVE_04
 ,  RESERVE_05
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DPC_TR
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
