CREATE VIEW CMDV_T_RCP_DPC_CD AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  OPRTN_YMD
 ,  PRAC_IDENT
 ,  ORDER_NO
 ,  ACT_DETL_NO
 ,  RCPT_COMP_SYS_REC
 ,  USE_AMNT
 ,  QNT_DAT
 ,  UNIT_CD
 ,  TIMES
 ,  SPCFC_DEV_NAME
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DPC_CD
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
