CREATE VIEW CMDV_T_RCP_PHA_YK AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  EXAM_PAY_INST
 ,  TDFK
 ,  SCORE_LIST
 ,  DRGST_CD
 ,  REQ_YM
 ,  MLT_VOL_IDENT_INFO
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_PHA_YK
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
