CREATE VIEW CMDV_T_RCP_PHA_RE AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  AGE
 ,  ID1
 ,  ID1N
 ,  ID2
 ,  RCP_NO
 ,  RCP_CLS
 ,  PRAC_YM
 ,  SEX_DIV
 ,  BIRTH_YM
 ,  PAY_RAT
 ,  RCPT_IMPTT_NOTI
 ,  TDFK
 ,  SCORE_LIST
 ,  MEDI_INST
 ,  RESERVE_01
 ,  SRCH_NO
 ,  REC_CNDTN_SPEC_YM_INFO
 ,  REQ_INFO
 ,  PART_BURD_DIV
 ,  INPUT_YM
 ,  AGE_HIER_CD1
 ,  AGE_HIER_CD2
 ,  LAST_BIRTH_AGE
 ,  LAST_BIRTH_AGE_HIER_CD1
 ,  LAST_BIRTH_AGE_HIER_CD2
  FROM
    TNDS_T_RCP_PHA_RE
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
