CREATE VIEW CMDV_T_RCP_PHA_HO AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  INSURER_NO
 ,  PRSPT_RCPTN_TIMES
 ,  TOTAL_SCORE
 ,  RESERVE_01
 ,  REASON_DUTY
 ,  PART_BURD
 ,  RESERVE_02
 ,  RDCT_TAX_DIV
 ,  RDCT_RAT
 ,  RDCT_PRICE
 ,  SUBSTR(LPAD(INSURER_NO_AFT,8,'0') , 1 , 2) AS HOUBETSU_NO
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_PHA_HO
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
