CREATE VIEW CMDV_T_RCP_PHA_KO AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  DEFRAYER_NO
 ,  EX_GRATIA_PAY_DIV
 ,  PRSPT_RCPTN_TIMES
 ,  TOTAL_SCORE
 ,  RESERVE_01
 ,  PART_BURD
 ,  RESERVE_02
 ,  PUB_MONEY_PAY_PART_BURD
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_PHA_KO
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
