CREATE VIEW CMDV_T_RCP_PHA_CZ AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  PRSPT_YMD
 ,  DSPNG_YMD
 ,  PRSPT_RCPTN_TIME
 ,  DSPNG_AMNT
 ,  DSC_BURD_DIV
 ,  DSC_CALC_DIV
 ,  DSC_CALC_NO
 ,  DSC_CD
 ,  DSC_SCORE
 ,  DVD_DVSN_DIV
 ,  DVD_LAST_AMNT
 ,  DRC_SCORE
 ,  RESERVE_01
 ,  ADC01_BURD_DIV
 ,  ADC01_CD
 ,  ADC01_SCORE
 ,  ADC02_BURD_DIV
 ,  ADC02_CD
 ,  ADC02_SCORE
 ,  ADC03_BURD_DIV
 ,  ADC03_CD
 ,  ADC03_SCORE
 ,  ADC04_BURD_DIV
 ,  ADC04_CD
 ,  ADC04_SCORE
 ,  ADC05_BURD_DIV
 ,  ADC05_CD
 ,  ADC05_SCORE
 ,  ADC06_BURD_DIV
 ,  ADC06_CD
 ,  ADC06_SCORE
 ,  ADC07_BURD_DIV
 ,  ADC07_CD
 ,  ADC07_SCORE
 ,  ADC08_BURD_DIV
 ,  ADC08_CD
 ,  ADC08_SCORE
 ,  ADC09_BURD_DIV
 ,  ADC09_CD
 ,  ADC09_SCORE
 ,  ADC10_BURD_DIV
 ,  ADC10_CD
 ,  ADC10_SCORE
 ,  PKG_DAYS
 ,  DVSN_DSPNG_TYPE
 ,  LAST_PKG_DAYS
 ,  DIV_DISPENSATION_CD
 ,  DIV_DISPENSATION_DIV
 ,  DIV_TARGET_DISP_QUANTITY
 ,  PACKAGE_DIV_NUM_DAYS
 ,  INCLUSION_MANAGEMENT_CHARGES
 ,  PRE_RECEPTION_OTHER_MED
 ,  PRSPT_NO
 ,  PRSPT_SUB_NO
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_PHA_CZ
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
