CREATE VIEW CMDV_T_RCP_PHA_TO AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  BURD_DIV
 ,  SPCFC_DEV_CD
 ,  USE_AMNT
 ,  UNIT_CD
 ,  UNIT_PRICE
 ,  SPCFC_DEV_NAME
 ,  PRSPT_NO
 ,  PRSPT_SUB_NO
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_PHA_TO
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
