CREATE VIEW CMDV_T_RCP_PHA_CO AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  CMT_CD
 ,  PRSPT_NO
 ,  PRSPT_SUB_NO
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_PHA_CO
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
