CREATE VIEW CMDV_T_RCP_DEN_RE AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  AGE
 ,  ID1
 ,  ID1N
 ,  ID2
 ,  RCP_NO
 ,  RCP_CLS
 ,  PRAC_YM
 ,  SEX_DIV
 ,  BIRTH_YM
 ,  PAY_RAT
 ,  HOSTZ_YMD
 ,  CNSLT_STR_YMD
 ,  OUTCM_DIV
 ,  WARD_DIV
 ,  STAND_BURD_DIV
 ,  RCPT_IMPTT_NOTI
 ,  RESERVE_01
 ,  REQ_INFO1
 ,  RESERVE_02
 ,  NON_HSPTL_VISIT_REQ
 ,  SRCH_NO
 ,  REC_CNDTN_YM_NO
 ,  REQ_INFO2
 ,  RESERVE_03
 ,  RESERVE_04
 ,  RESERVE_05
 ,  INPUT_YM
 ,  AGE_HIER_CD1
 ,  AGE_HIER_CD2
 ,  LAST_BIRTH_AGE
 ,  LAST_BIRTH_AGE_HIER_CD1
 ,  LAST_BIRTH_AGE_HIER_CD2
  FROM
    TNDS_T_RCP_DEN_RE
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
