CREATE VIEW CMDV_T_RCP_DEN_KO AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  DEFRAYER_NO
 ,  EX_GRATIA_PAY_DIV
 ,  PRAC_TRUE_DAYS
 ,  TOTAL_SCORE
 ,  PUB_MONEY
 ,  PUB_MONEY_PAY_BURD
 ,  TIMES
 ,  TOTAL_PRICE
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DEN_KO
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
