CREATE VIEW CMDV_T_RCP_DEN_HS AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  PRAC_STR_YMD
 ,  OUTCM_DIV
 ,  SKWD_NAME_DF
 ,  SKWD_NAME_CD
 ,  MODIF_CD
 ,  SSPCT_DSS_FLG
 ,  SKWD_NAME
 ,  COEX_SKWD_NUM
 ,  PATHL_TRANS
 ,  MAIN_SKWD
 ,  CMT_CD
 ,  SPLMT_CMT
 ,  SPLMT_CMT_DF
 ,  MAIN_SKWD_DECIS_FLG
 ,  MAIN_SKWD_DECIS_ERR
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DEN_HS
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
