CREATE VIEW CMDV_T_RCP_DEN_TO AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  PRAC_IDENT
 ,  BURD_DIV
 ,  SPCFC_DEV_CD
 ,  USE_AMNT
 ,  UNIT_CD
 ,  UNIT_PRICE
 ,  SPCFC_DEV_ADD1_CD
 ,  SPCFC_DEV_ADD_AMNT1_DAT
 ,  SPCFC_DEV_ADD2_CD
 ,  SPCFC_DEV_ADD_AMNT2_DAT
 ,  SPCFC_DEV_TRD_NAME_STD_SZ
 ,  SCORE
 ,  TIMES
 ,  DAYS01_INFO
 ,  DAYS02_INFO
 ,  DAYS03_INFO
 ,  DAYS04_INFO
 ,  DAYS05_INFO
 ,  DAYS06_INFO
 ,  DAYS07_INFO
 ,  DAYS08_INFO
 ,  DAYS09_INFO
 ,  DAYS10_INFO
 ,  DAYS11_INFO
 ,  DAYS12_INFO
 ,  DAYS13_INFO
 ,  DAYS14_INFO
 ,  DAYS15_INFO
 ,  DAYS16_INFO
 ,  DAYS17_INFO
 ,  DAYS18_INFO
 ,  DAYS19_INFO
 ,  DAYS20_INFO
 ,  DAYS21_INFO
 ,  DAYS22_INFO
 ,  DAYS23_INFO
 ,  DAYS24_INFO
 ,  DAYS25_INFO
 ,  DAYS26_INFO
 ,  DAYS27_INFO
 ,  DAYS28_INFO
 ,  DAYS29_INFO
 ,  DAYS30_INFO
 ,  DAYS31_INFO
 ,  AFT_SPLMT_PRAC_IDENT
 ,  SERL_NO
 ,  SERS_ODR
 ,  AFT_SPLMT_SCORE
 ,  AFT_SPLMT_SCORE_ERR
 ,  AFT_SPLMT_TIMES
 ,  AFT_SPLMT_TIMES_ERR
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DEN_TO
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
