CREATE VIEW CMDV_T_RCP_DEN_CO AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  PRAC_IDENT
 ,  BURD_DIV
 ,  CMT_CD
 ,  CMT_DF
 ,  RESERVE_01
 ,  RESERVE_02
 ,  RESERVE_03
 ,  RESERVE_04
 ,  RESERVE_05
 ,  AFT_SPLMT_PRAC_IDENT
 ,  SERL_NO
 ,  SERS_ODR
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_DEN_CO
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
