CREATE VIEW CMDV_T_RCP_MED_GR AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  YIELD_CALC_REASON
 ,  DIAG_GRP_CLS_NO
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_MED_GR
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
