CREATE VIEW CMDV_T_RCP_PHA_ST AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  REC_IDENT_INFO
 ,  PRSPT_YMD
 ,  DSPNG_YMD
 ,  PRSPT_RCPTN_TIME
 ,  DIV_NUM_TIME_DIRECTIONS
 ,  DIV_HO_TARGET_SCORE
 ,  SCORE_AFTER_DIV_HO
 ,  DIV01_TARGET_SCORE
 ,  SCORE_AFTER_DIV01
 ,  DIV02_TARGET_SCORE
 ,  SCORE_AFTER_DIV02
 ,  DIV03_TARGET_SCORE
 ,  SCORE_AFTER_DIV03
 ,  DIV04_TARGET_SCORE
 ,  SCORE_AFTER_DIV04
 ,  PRAC_YM
 ,  INPUT_YM
  FROM
    TNDS_T_RCP_PHA_ST
  WHERE
    KO_FLG IN (0,2)
WITH READ ONLY
;
