-- IY_DATAにデータを挿入して、サマリーする一連のクエリを繰り返し、最終結果を出力するバッチ

-- 対象となる疾患を定義
-- 疾患毎に変更する
DEFINE DISEASE = 'Dyslipidemia'

-- ログを保存
SPOOL SPOOL_&DISEASE..log

-- タイム測定開始
TIMING START

-- 対象となる医薬品の情報を持つTABLE MEDICINE_CD_EXTRACTを作成
@&DISEASE/CREATE_TABLE_MEDICINE_CD_EXTRACT.sql

-- 一年ずつ区切ってクエリを繰り返す
-- 期間の変数を定義
DEFINE START_YM = '42104'
DEFINE END_YM = '42203'

-- &START_YMから&END_YMまでの期間のIY_DATAをINSERTし、サマリーを作成するバッチ
@BATCH_SUMMARY.sql

-- 繰り返し
DEFINE START_YM = '42204'
DEFINE END_YM = '42303'
@BATCH_SUMMARY.sql

DEFINE START_YM = '42304'
DEFINE END_YM = '42403'
@BATCH_SUMMARY.sql

DEFINE START_YM = '42404'
DEFINE END_YM = '42503'
@BATCH_SUMMARY.sql

DEFINE START_YM = '42504'
DEFINE END_YM = '42603'
@BATCH_SUMMARY.sql

DEFINE START_YM = '42604'
DEFINE END_YM = '42703'
@BATCH_SUMMARY.sql

-- 最終タイム
TIMING STOP

-- MEDICINE_CD_EXTRACTはこの後使わないのでDROP
TRUNCATE TABLE MEDICINE_CD_EXTRACT;
DROP TABLE MEDICINE_CD_EXTRACT;

-- サマリーをcsv出力する
-- ログの保存を停止
SPOOL OFF

-- CSV出力のための設定
SET ECHO OFF
SET LINESIZE 1000
SET PAGESIZE 0
SET FEEDBACK OFF

-- SUMMARY_1から集計結果をcsv出力
@OUTPUT_SUMMARY_1_CSV.sql

-- SUMMARY_2から集計結果をcsv出力
@OUTPUT_SUMMARY_2_CSV.sql

-- 設定を戻す
SET ECHO ON
SET LINESIZE 32767
SET PAGESIZE 50000
SET FEEDBACK ON

-- 次の疾患の実行のためにサマリーをTRUNCATE
TRUNCATE TABLE SUMMARY_1;
TRUNCATE TABLE SUMMARY_2;
DROP VIEW SUMMARY_1_TIDY;
DROP VIEW SUMMARY_2_TIDY;
