-- TARGET_PHA_CZ‚ÆTARGET_PHA_IY‚ðJOIN‚µ‚Ä•K—v‚Èî•ñ‚ð’Šo‚µ‚½TABLE TARGET_PHA_CZIY
CREATE  TABLE   TARGET_PHA_CZIY(SEQ2_NO, DSPNG_AMNT, MEDICINE_CD, USE_AMNT) AS
SELECT
    CZ.SEQ2_NO
,   CZ.DSPNG_AMNT
,   IY.MEDICINE_CD
,   IY.USE_AMNT
FROM
    TARGET_PHA_CZ   CZ
,   TARGET_PHA_IY   IY
WHERE
    CZ.SEQ2_NO  =   IY.SEQ2_NO
AND CZ.PRSPT_NO =   IY.PRSPT_NO
;
