-- 疾患に対応する傷病コードのある個人のID1を持つTABLE TARGET_ID1
-- 今回の対象は20歳以上の人のみ
CREATE  TABLE   TARGET_ID1(ID1) AS
SELECT DISTINCT
    RE.ID1
FROM
    CMDV_T_RCP_MED_RE RE
WHERE
    RE.AGE      >=  20
AND RE.PRAC_YM  >=  &START_YM
AND RE.PRAC_YM  <=  &END_YM
AND RE.VLD_FLG  =   1
AND EXISTS(
  SELECT *
  FROM INIT_SEQ TS
  WHERE TS.SEQ2_NO = RE.SEQ2_NO
)
;
