-- RCP_CLS_MASTER‚É“ü‚Á‚Ä‚¢‚éCOSTSHARING‚Ì'10','20','1020'‚ð'10'‚É‚Ü‚Æ‚ß‚éVIEW
CREATE OR REPLACE   VIEW    RCP_CLS_MASTER_SIMPLE(RCP_CLS, ADMISSION, PRESCRIPTION, PUBFUND, COSTSHARING)   AS
SELECT
    RCP_CLS
,   ADMISSION
,   PRESCRIPTION
,   PUBFUND
,   CASE
        WHEN
            COSTSHARING =   '10'
        OR  COSTSHARING =   '20'
        OR  COSTSHARING =   '1020'
        THEN
            '10'
        ELSE
            COSTSHARING
    END
FROM
    RCP_CLS_MASTER
;