-- SUMMARY_1から集計結果をcsv出力
-- 名称をわかりやすいものに変更する
CREATE OR REPLACE   VIEW    SUMMARY_1_TIDY(GENERIC_SHARE, INGREDIENT, DISEASE, SEIREKI_NAME, TDFK_NAME, AGE, SEX_DIV_NAME, TOTAL_AMNT)   AS
SELECT
    S1.GENERIC_SHARE
,   MT.INGREDIENT
,   MT.DISEASE
,   TTTJY.SEIREKI_NAME
,   TMPPT.TDFK_NAME
,   S1.AGE
,   CMSD.SEX_DIV_NAME
,   S1.TOTAL_AMNT
FROM
    SUMMARY_1           S1
,   MEDICATION_TABLE        MT
,   TNDS_T_TRANS_JC_YEAR    TTTJY
,   (SELECT DISTINCT TDFK_CD, TDFK_NAME FROM TNDS_M_POP_PER_TDFK)     TMPPT
,   CMDS_M_SEX_DIV          CMSD
WHERE
    S1.MEDICINE_SHORT  =   MT.MEDICINE_SHORT
AND S1.PRAC_YM         =   TTTJY.WAREKI
AND S1.TDFK            =   TMPPT.TDFK_CD
AND S1.SEX_DIV         =   CMSD.SEX_DIV
;
SPOOL   SUMMARY_1_&DISEASE..csv
SELECT
    GENERIC_SHARE   ||','|| INGREDIENT  ||','|| DISEASE  ||','|| SEIREKI_NAME    ||','|| TDFK_NAME   ||','|| AGE ||','|| SEX_DIV_NAME    ||','|| TOTAL_AMNT
FROM
    SUMMARY_1_TIDY
ORDER BY
    INGREDIENT
,   SEIREKI_NAME
,   TDFK_NAME
,   AGE
,   SEX_DIV_NAME
;
SPOOL   OFF