-- SUMMARY_2から集計結果をcsv出力
-- 名称をわかりやすいものに変更する
CREATE OR REPLACE   VIEW    SUMMARY_2_TIDY(GENERIC_SHARE, INGREDIENT, DISEASE, SEIREKI_NAME, TDFK_NAME, AGE, SEX_DIV_NAME, PUBFUND, COSTSHARING, TOTAL_AMNT) AS
SELECT
    S2.GENERIC_SHARE
,   MT.INGREDIENT
,   MT.DISEASE
,   TTTJY.SEIREKI_NAME
,   TMPPT.TDFK_NAME
,   S2.AGE
,   CMSD.SEX_DIV_NAME
,   S2.PUBFUND
,   S2.COSTSHARING
,   S2.TOTAL_AMNT
FROM
    SUMMARY_2           S2
,   MEDICATION_TABLE        MT
,   TNDS_T_TRANS_JC_YEAR    TTTJY
,   (SELECT DISTINCT TDFK_CD, TDFK_NAME FROM TNDS_M_POP_PER_TDFK)     TMPPT
,   CMDS_M_SEX_DIV          CMSD
WHERE
    S2.MEDICINE_SHORT  =   MT.MEDICINE_SHORT
AND S2.PRAC_YM         =   TTTJY.WAREKI
AND S2.TDFK            =   TMPPT.TDFK_CD
AND S2.SEX_DIV         =   CMSD.SEX_DIV
;
SPOOL   SUMMARY_2_&DISEASE..csv
SELECT
    GENERIC_SHARE   ||','|| INGREDIENT  ||','|| DISEASE  ||','|| SEIREKI_NAME    ||','|| TDFK_NAME   ||','|| AGE ||','|| SEX_DIV_NAME    ||','|| PUBFUND ||','|| COSTSHARING ||','|| TOTAL_AMNT
FROM
    SUMMARY_2_TIDY
ORDER BY
    INGREDIENT
,   SEIREKI_NAME
,   TDFK_NAME
,   AGE
,   SEX_DIV_NAME
,   PUBFUND
,   COSTSHARING
;
SPOOL   OFF