@ddl/11_SONOTA/08_CREATE_TABLE_TNDS_T_MSTLINK.sql
@ddl/11_SONOTA/09_CREATE_TABLE_TNDS_T_TRANS_JC_YEAR.sql
@ddl/11_SONOTA/10_CREATE_TABLE_TNDS_T_AGE_DIV1.sql
@ddl/11_SONOTA/11_CREATE_TABLE_TNDS_T_AGE_DIV2.sql
