DROP TABLE TNDS_T_MSTLINK CASCADE CONSTRAINTS PURGE;
DROP TABLE TNDS_T_TRANS_JC_YEAR CASCADE CONSTRAINTS PURGE;
DROP TABLE TNDS_T_AGE_DIV1 CASCADE CONSTRAINTS PURGE;
DROP TABLE TNDS_T_AGE_DIV2 CASCADE CONSTRAINTS PURGE;
