CREATE TABLE TNDS_T_AGE_DIV1
(
AGE_HIER_CODE                VARCHAR2 (3) NOT NULL ENABLE,
AGE_HIER                     NVARCHAR2(10),
    CONSTRAINT TNDS_T_AGE_DIV1_PK PRIMARY KEY (AGE_HIER_CODE) USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
