-- テスト環境を補うための追加データ
-- SQL*Plusで接続する度に実行する

-- テスト用のTNDS_M_MEDICINEをTEMPORARY TABLEで作成
@CREATE_TNDS_M_MEDICINE.sql

-- テスト用のTNDS_M_POP_PER_TDFKをTEMPORARY TABLEで作成
@CREATE_TNDS_M_POP_PER_TDFK.sql

-- テスト用のTNDS_T_TRANS_JC_YEARをINSERT
@CREATE_TNDS_T_TRANS_JC_YEAR.sql
