--TNDS_M_POP_PER_TDFKに該当するTEST DATA
--TDFK_CDとTDFK_NAMEのみ使用する

DROP TABLE TNDS_M_POP_PER_TDFK;

CREATE GLOBAL TEMPORARY TABLE TNDS_M_POP_PER_TDFK
(
	TDFK_CD VARCHAR2 (2) NOT NULL,
	TDFK_NAME NVARCHAR2 (12)
	) ON COMMIT PRESERVE ROWS;

INSERT INTO TNDS_M_POP_PER_TDFK VALUES ('13','東京都');