-- テスト環境を補うための追加データを初期化する

-- 新たにINSERTしたデータをTRUNCATE
TRUNCATE TABLE TNDS_T_TRANS_JC_YEAR;
-- 新たに作成したTEMPORARY TABLEをDROP
TRUNCATE TABLE TNDS_M_MEDICINE;
TRUNCATE TABLE TNDS_M_POP_PER_TDFK;
DROP TABLE TNDS_M_MEDICINE;
DROP TABLE TNDS_M_POP_PER_TDFK;
