-- IY_DATAに挿入するデータ
-- 院内処方
INSERT
/*+
    APPEND
*/
INTO
    IY_DATA
SELECT
    RE.PRAC_YM
,   IR.TDFK
,   RE.AGE
,   RE.RCP_CLS
,   RE.SEX_DIV
,   MCE.MEDICINE_SHORT
,   MCE.GENERIC
,   IY.USE_AMNT*IY.TIMES
FROM
    TARGET_MED_RE       RE
,   MEDICINE_CD_EXTRACT MCE
,   TARGET_MED_IR       IR
,   TARGET_MED_IY       IY
WHERE
    RE.SEQ2_NO      =   IY.SEQ2_NO
AND RE.PRAC_YM      =   MCE.APPL_YM_W
AND RE.SEQ2_NO      =   IR.SEQ2_NO
AND IY.MEDICINE_CD  =   MCE.MEDICINE_CD
;
COMMIT
;
