-- IY_DATAに挿入するデータ
-- 院外処方
INSERT
/*+
    APPEND
*/
INTO
    IY_DATA
SELECT
    RE.PRAC_YM
,   YK.TDFK
,   RE.AGE
,   RE.RCP_CLS
,   RE.SEX_DIV
,   MCE.MEDICINE_SHORT
,   MCE.GENERIC
,   CZIY.USE_AMNT*CZIY.DSPNG_AMNT
FROM
    TARGET_PHA_RE       RE
,   MEDICINE_CD_EXTRACT MCE
,   TARGET_PHA_YK       YK
,   TARGET_PHA_CZIY     CZIY
WHERE
    RE.SEQ2_NO          =   YK.SEQ2_NO
AND RE.SEQ2_NO          =   CZIY.SEQ2_NO
AND RE.PRAC_YM          =   MCE.APPL_YM_W
AND CZIY.MEDICINE_CD    =   MCE.MEDICINE_CD
;
COMMIT
;
