CREATE VIEW CMDV_T_TOKKEN_BASE AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  IDENT_CD
 ,  ID1
 ,  ID1N
 ,  ID2
 ,  AGE
 ,  TESTEE_POST_NO
 ,  TESTEE_SEX_CD
 ,  TESTEE_BIRTH_YM
 ,  CNSLT_TCKT_FACE_CLS
 ,  CNSLT_TCKT_RFRNC_NO
 ,  MEE_PRG_CLS
 ,  MEE_YMD
 ,  MEE_INST_NO
 ,  INSURER_NO
 ,  RPT_DIV
 ,  QLFCT_DIV
 ,  INPUT_YM
 ,  AGE_HIER_CD1
 ,  AGE_HIER_CD2
 ,  LAST_BIRTH_AGE
 ,  LAST_BIRTH_AGE_HIER_CD1
 ,  LAST_BIRTH_AGE_HIER_CD2
 ,  MEE_NENDO
  FROM
    TNDS_T_TOKKEN_BASE
WITH READ ONLY
;
