CREATE VIEW CMDV_T_THOKEN_BASE AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  IDENT_CD
 ,  ID1
 ,  ID1N
 ,  ID2
 ,  AGE
 ,  USER_POST_NO
 ,  USER_SEX_CD
 ,  USER_BIRTH_YM
 ,  CNSLT_TCKT_FACE_CLS
 ,  CNSLT_TCKT_RFRNC_NO
 ,  USE_TCKT_FACE_CLS
 ,  USE_TCKT_RFRNC_NO
 ,  HGE_PRG_CLS
 ,  HGE_YMD
 ,  HG_PRG_NAME
 ,  HGE_INST_NO
 ,  INSURER_NO
 ,  RPT_DIV
 ,  QLFCT_DIV
 ,  INPUT_YM
 ,  AGE_HIER_CD1
 ,  AGE_HIER_CD2
 ,  LAST_BIRTH_AGE
 ,  LAST_BIRTH_AGE_HIER_CD1
 ,  LAST_BIRTH_AGE_HIER_CD2
 ,  HGE_NENDO
  FROM
    TNDS_T_THOKEN_BASE
WITH READ ONLY
;
