CREATE VIEW CMDV_T_THOKEN_FACE AS
  SELECT
    SEQ1_NO
 ,  SEQ2_NO
 ,  VLD_FLG
 ,  IDENT_CD
 ,  CNSLT_TCKT_FACE_CLS
 ,  CNSLT_TCKT_RFRNC_NO
 ,  HGE_NENDO
 ,  INPUT_YM
  FROM
    TNDS_T_THOKEN_FACE
WITH READ ONLY
;
