CREATE TABLE TNDS_M_SKWD
(
CHG_DIV                      VARCHAR2 (1),
MST_CLS                      VARCHAR2 (1),
SKWD_NAME_CD                 VARCHAR2 (7) NOT NULL ENABLE,
TRANS_CD                     VARCHAR2 (7),
SKWD_STD_NAME_DIG            NUMBER   (2,0),
SKWD_STD_NAME                NVARCHAR2(30),
SKWD_RYK_NAME_DIG            NUMBER   (2,0),
SKWD_RYK_NAME                NVARCHAR2(20),
SKWD_KANA_NAME_DIG           NUMBER   (2,0),
SKWD_KANA_NAME               NVARCHAR2(50),
DSS_NAME_MNG_NO              VARCHAR2 (8),
SEL_DIV                      VARCHAR2 (1),
DSS_NAME_EXCHG_CD            VARCHAR2 (4),
ICD_10_1                     VARCHAR2 (5),
ICD_10_2                     VARCHAR2 (5),
RESERVE_01                   VARCHAR2 (5),
RESERVE_02                   VARCHAR2 (5),
RESERVE_03                   VARCHAR2 (5),
USE_ALN_PRHBT_DIV            VARCHAR2 (2),
INSU_REQ_OUT_DIV             VARCHAR2 (1),
SPCFC_DSS_DIV                VARCHAR2 (2),
LST_YMD                      VARCHAR2 (8),
CHG_YMD                      VARCHAR2 (8),
ABO_YMD                      VARCHAR2 (8),
CI_SKWD_STD_NAME             VARCHAR2 (1),
CI_SKWD_RYK_NAME             VARCHAR2 (1),
CI_SKWD_KANA_NAME            VARCHAR2 (1),
CI_SEL_DIV                   VARCHAR2 (1),
CI_DSS_NAME_EXCHG_CD         VARCHAR2 (1),
CI_ICD_10_1                  VARCHAR2 (1),
CI_ICD_10_2                  VARCHAR2 (1),
CI_DENT_SKWD_RYK_NAME        VARCHAR2 (1),
CI_OUTPT_INC_DSS_DIV         VARCHAR2 (1),
CI_DEN_SPCFC_DSS_TRGT_DIV    VARCHAR2 (1),
CI_USE_ALN_PRHBT_DIV         VARCHAR2 (1),
CI_INSU_REQ_OUT_DIV          VARCHAR2 (1),
CI_SPCFC_DSS_DIV             VARCHAR2 (1),
TRANS_DSS_NAME_MNG_NO        VARCHAR2 (8),
DEN_SKWD_RYK_NAME            NVARCHAR2(20),
RESERVE_04                   VARCHAR2 (10),
RESERVE_05                   VARCHAR2 (8),
DEN_SKWD_RYK_NAME_DIG        NUMBER   (2,0),
OUTPT_INC_DSS_DIV            VARCHAR2 (2),
DEN_SPCFC_DSS_TRGT_DIV       VARCHAR2 (2),
RESERVE_06                   VARCHAR2 (2),
INPUT_YMD                    VARCHAR2 (8),
APPL_YM                      VARCHAR2 (6),
MST_GEN                      VARCHAR2 (9) NOT NULL ENABLE,
    CONSTRAINT TNDS_M_SKWD_PK PRIMARY KEY (MST_GEN,SKWD_NAME_CD) USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 30
;
