CREATE TABLE TNDS_M_PRAC_ACT
(
CHG_DIV                      VARCHAR2 (1),
MST_CLS                      VARCHAR2 (1),
PRAC_ACT_CD                  VARCHAR2 (9) NOT NULL ENABLE,
PARN_RYK_KANJ_VLD_DIG        NUMBER   (2,0),
PARN_RYK_KANJ                NVARCHAR2(32),
PARN_RYK_KANA_VLD_DIG        NUMBER   (2,0),
PARN_RYK_KANA                NVARCHAR2(20),
DAT_STD_COD                  VARCHAR2 (3),
DSN_KANJ_VLD_DIG             VARCHAR2 (1),
DSN_KANJ                     NVARCHAR2(6),
NNS_SCORE_IDENT              VARCHAR2 (1),
NNS_NEW_NOW_SCORE            NUMBER   (9,2),
IN_OUT_APPL_DIV              VARCHAR2 (1),
OLD_OLD_APPL_DIV             VARCHAR2 (1),
SCORE_CNT_OUT_IDENT          VARCHAR2 (3),
INCL_EXAM                    VARCHAR2 (2),
RESERVE_01                   VARCHAR2 (1),
DPC_APPL_DIV                 VARCHAR2 (1),
HSPTL_MEDI_OFC_DIV           VARCHAR2 (1),
IMG_SURG_SPRT_ADD            VARCHAR2 (1),
LAW_CNCRN_MEDI_OBS_DIV       VARCHAR2 (1),
NURS_ADD                     VARCHAR2 (2),
ANEST_IDENT_DIV              VARCHAR2 (1),
HOSTZ_BSC_CHRG_ADD_DIV       VARCHAR2 (3),
SKWD_ASCT_DIV                VARCHAR2 (2),
MEDI_MNG_CHARGE              VARCHAR2 (2),
TRUE_DAYS                    VARCHAR2 (1),
DAYS_TIMES                   VARCHAR2 (1),
MDC_ASCT_DIV                 VARCHAR2 (1),
NV_NOTC_CALC_IDENT           VARCHAR2 (1),
NV_LWR_VAL                   NUMBER   (8,0),
NV_UPR_VAL                   NUMBER   (8,0),
NV_NOTC_VAL                  NUMBER   (8,0),
NV_NOTC_SCORE                NUMBER   (9,2),
NV_LMT_ERR                   VARCHAR2 (1),
ULT_UPR_TIMES                NUMBER   (3,0),
ULT_UPR_TIMES_ERR            VARCHAR2 (1),
NA_NOTE_ADD_CD               VARCHAR2 (4),
NA_NOTE_ADD_SERL_NO          VARCHAR2 (1),
CMN_RULE_AGE                 VARCHAR2 (1),
LMT_AGE_LWR                  VARCHAR2 (2),
LMT_AGE_UPR                  VARCHAR2 (2),
TIME_ADD_DIV                 VARCHAR2 (1),
SMI_MATCH_CD                 VARCHAR2 (1),
SMI_TGT_EQP_STD              VARCHAR2 (4),
TRT_INFANT_ADD_DIV           VARCHAR2 (1),
LOW_WT_INFANT_ADD_DIV        VARCHAR2 (1),
HOSTZ_BSC_CHRG_SUB_IDENT     VARCHAR2 (1),
DONOR_CNT_DIV                VARCHAR2 (1),
EXAM_OPRTN_JUDGE_DIV         VARCHAR2 (1),
EXAM_OPRTN_JUDGE_GRP_DIV     VARCHAR2 (2),
GRDL_DMNTN_DIV               VARCHAR2 (1),
SEPM_ADD_DIV                 VARCHAR2 (1),
RND_ADD_DIV                  VARCHAR2 (1),
AUTO_SUTUR_ADD_DIV           VARCHAR2 (1),
OUTPT_MNG_ADD_DIV            VARCHAR2 (1),
OS_SCORE_IDENT               VARCHAR2 (1),
OS_OLD_SCORE                 NUMBER   (9,2),
KANJ_CHG_DIV                 VARCHAR2 (1),
KANA_CHG_DIV                 VARCHAR2 (1),
LABO_TEST_CMT                VARCHAR2 (1),
CRAPS_DIV                    VARCHAR2 (1),
INCL_GRDL_DMNTN_DIV          VARCHAR2 (3),
UTSNC_EDSCP_ADD_DIV          VARCHAR2 (1),
RESERVE_02                   VARCHAR2 (2),
SCORE_CNT_HOSTZ_IDENT        VARCHAR2 (3),
AUTO_ANAST_DEV_ADD_DIV       VARCHAR2 (1),
NOTIF_IDENT1_DIV             VARCHAR2 (1),
NOTIF_IDENT2_DIV             VARCHAR2 (1),
LOC_ADD                      VARCHAR2 (1),
BED_CAPA_DIV                 VARCHAR2 (1),
ES01_EQP_STD_CD              VARCHAR2 (4),
ES02_EQP_STD_CD              VARCHAR2 (4),
ES03_EQP_STD_CD              VARCHAR2 (4),
ES04_EQP_STD_CD              VARCHAR2 (4),
ES05_EQP_STD_CD              VARCHAR2 (4),
ES06_EQP_STD_CD              VARCHAR2 (4),
ES07_EQP_STD_CD              VARCHAR2 (4),
ES08_EQP_STD_CD              VARCHAR2 (4),
ES09_EQP_STD_CD              VARCHAR2 (4),
ES10_EQP_STD_CD              VARCHAR2 (4),
SWCD_ADD_DIV                 VARCHAR2 (1),
SHORT_STAY_SURG              VARCHAR2 (1),
DENT_APPL_DIV                VARCHAR2 (1),
CD_LST_NO                    VARCHAR2 (1),
NOTIF_ASCT_NO                VARCHAR2 (1),
CHG_YMD                      VARCHAR2 (8),
ABO_YMD                      VARCHAR2 (8),
PBLCT_ODR_NO                 VARCHAR2 (9),
CLN_CHAP                     VARCHAR2 (1),
CLN_PART                     VARCHAR2 (2),
CLN_DIV_NO                   VARCHAR2 (3),
CLN_BRNC_NO                  VARCHAR2 (2),
CLN_ITEM_NO                  VARCHAR2 (2),
NAN_CHAP                     VARCHAR2 (1),
NAN_PART                     VARCHAR2 (2),
NAN_DIV_NO                   VARCHAR2 (3),
NAN_BRNC_NO                  VARCHAR2 (2),
NAN_ITEM_NO                  VARCHAR2 (2),
AA01_LWR                     VARCHAR2 (2),
AA01_UPR                     VARCHAR2 (2),
AA01_NOTE_ADD_PRAC_ACT_CD    VARCHAR2 (9),
AA02_LWR                     VARCHAR2 (2),
AA02_UPR                     VARCHAR2 (2),
AA02_NOTE_ADD_PRAC_ACT_CD    VARCHAR2 (9),
AA03_LWR                     VARCHAR2 (2),
AA03_UPR                     VARCHAR2 (2),
AA03_NOTE_ADD_PRAC_ACT_CD    VARCHAR2 (9),
AA04_LWR                     VARCHAR2 (2),
AA04_UPR                     VARCHAR2 (2),
AA04_NOTE_ADD_PRAC_ACT_CD    VARCHAR2 (9),
TNOV_ASCT                    VARCHAR2 (9),
BASE_KANJ_NAME               NVARCHAR2(64),
EPSO_ADD                     VARCHAR2 (1),
BTEA_PSO_ADD                 VARCHAR2 (1),
LTAM_ADD                     VARCHAR2 (1),
SCORE_DIV_NUM                VARCHAR2 (30),
H_MON_ADD                    VARCHAR2 (1),
C_SIM_O_ADD                  VARCHAR2 (1),
RESERVE_05                   NUMBER   (3,0),
RESERVE_06                   NUMBER   (9,0),
RESERVE_07                   NUMBER   (9,0),
INPUT_YMD                    VARCHAR2 (8),
APPL_YM                      VARCHAR2 (6),
MST_GEN                      VARCHAR2 (9) NOT NULL ENABLE,
    CONSTRAINT TNDS_M_PRAC_ACT_PK PRIMARY KEY (MST_GEN,PRAC_ACT_CD) USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 30
;
