CREATE TABLE TNDS_M_DEN_BASE
(
CHG_DIV                      VARCHAR2 (1),
MST_CLS                      VARCHAR2 (1),
PRAC_ACT_CD                  VARCHAR2 (9) NOT NULL ENABLE,
NOTIF_NO_DIV                 VARCHAR2 (1),
NOTIF_NO_DIV_NO              VARCHAR2 (3),
NOTIF_NO_BRNC_NO             VARCHAR2 (2),
NOTIF_NO_ITEM_NO             VARCHAR2 (2),
ADD_CD                       VARCHAR2 (5),
PAN_STD_NAME                 NVARCHAR2(100),
PAN_RYK_NAME                 NVARCHAR2(32),
NNS_SCORE_IDENT              VARCHAR2 (1),
NNS_SCORE                    NUMBER   (9,2),
OS_SCORE_IDENT               VARCHAR2 (1),
OS_OLD_SCORE                 NUMBER   (9,2),
IN_OUT_APPL_DIV              VARCHAR2 (1),
OLD_OLD_MEDI_APPL_DIV        VARCHAR2 (1),
TIME_ADD_DIV                 VARCHAR2 (1),
HSPTL_MEDI_OFC_DIV           VARCHAR2 (1),
CARE_ADD                     VARCHAR2 (2),
RESERVE_01                   NUMBER   (3,0),
RESERVE_04                   VARCHAR2 (2),
LOC_ADD                      VARCHAR2 (1),
SKWD_ASCT_DIV                VARCHAR2 (2),
MDC_ASCT_DIV                 VARCHAR2 (1),
BED_CAPA_DIV                 VARCHAR2 (1),
FILING                       VARCHAR2 (2),
NON_HSPTL_VISIT              VARCHAR2 (1),
SHORT_STAY_SURG              VARCHAR2 (1),
IMPTT_NOTI                   VARCHAR2 (1),
EXAM_OPRTN_JUDGE_DIV         VARCHAR2 (1),
EXAM_OPRTN_JUDGE_GRP_DIV     VARCHAR2 (2),
GRDL_DMNTN_DIV               VARCHAR2 (1),
INCL_GRDL_DMNTN_DIV          VARCHAR2 (3),
SMI_MATCH_CD                 VARCHAR2 (1),
SMI_TGT_EQP_STD              VARCHAR2 (4),
ES01_EQP_STD_CD              VARCHAR2 (4),
ES02_EQP_STD_CD              VARCHAR2 (4),
ES03_EQP_STD_CD              VARCHAR2 (4),
ES04_EQP_STD_CD              VARCHAR2 (4),
ES05_EQP_STD_CD              VARCHAR2 (4),
ES06_EQP_STD_CD              VARCHAR2 (4),
ES07_EQP_STD_CD              VARCHAR2 (4),
ES08_EQP_STD_CD              VARCHAR2 (4),
ES09_EQP_STD_CD              VARCHAR2 (4),
ES10_EQP_STD_CD              VARCHAR2 (4),
CRA_GRP                      VARCHAR2 (4),
BA_GRP                       VARCHAR2 (4),
NA_GRP                       VARCHAR2 (4),
MCA_GRP                      VARCHAR2 (4),
CTL_TBL_IDENT                VARCHAR2 (1),
NOTC_TBL_IDENT               VARCHAR2 (1),
AL_TBL_IDENT                 VARCHAR2 (1),
TCR_TBL_IDENT                VARCHAR2 (1),
TD_TBL_IDENT                 VARCHAR2 (1),
RESERVE_02                   NUMBER   (3,0),
RESERVE_03                   NUMBER   (3,0),
CHG_YMD                      VARCHAR2 (8),
ABO_YMD                      VARCHAR2 (8),
LTIME_ANESTHETIC_ADD         VARCHAR2 (1),
GRULE_ADD_S_TARGET_DIV       VARCHAR2 (1),
RESERVE_06                   NUMBER   (3,0),
RESERVE_07                   NUMBER   (3,0),
RESERVE_08                   NUMBER   (3,0),
PBLCT_ODR_NO                 VARCHAR2 (9),
INPUT_YMD                    VARCHAR2 (8),
APPL_YM                      VARCHAR2 (6),
MST_GEN                      VARCHAR2 (9) NOT NULL ENABLE,
    CONSTRAINT TNDS_M_DEN_BASE_PK PRIMARY KEY (MST_GEN,PRAC_ACT_CD) USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 30
;
