CREATE TABLE TNDS_M_DSPNG_ACT
(
CHG_DIV                      VARCHAR2 (1),
MST_CLS                      VARCHAR2 (1),
DSPNG_ACT_CD                 VARCHAR2 (9) NOT NULL ENABLE,
DAN_KANJ_VLD_DIG             NUMBER   (2,0),
DAN_KANJ                     NVARCHAR2(32),
DAN_KANA_VLD_DIG             NUMBER   (2,0),
DAN_KANA                     NVARCHAR2(20),
RD_SMBL_CD                   VARCHAR2 (2),
RD_TURN_NO                   VARCHAR2 (2),
NNS_SCORE_IDENT              VARCHAR2 (1),
DSPNG_AMNT_CALC_FLG          VARCHAR2 (1),
SC_NEW_NOW_SCORE             NUMBER   (9,2),
SC_NOTC_CALC_IDENT           VARCHAR2 (1),
SC_LWR_VAL                   NUMBER   (3,0),
SC_UPR_VAL                   NUMBER   (3,0),
SC_NOTC_VAL                  NUMBER   (3,0),
SC_NOTC_SCORE                NUMBER   (9,2),
SC_LMT_ERR                   VARCHAR2 (1),
SUBTRACTION_ACT_DIV          VARCHAR2 (1),
SUBTRACTION_TARGET_ACT_DIV   VARCHAR2 (1),
D_ACT_DISINCTION_DIV         VARCHAR2 (2),
INCLUSION_DISTINCTION_DIV    VARCHAR2 (1),
RESERVE_05                   NUMBER   (9,0),
RESERVE_06                   NUMBER   (9,0),
RESERVE_07                   NUMBER   (3,0),
RESERVE_08                   NUMBER   (3,0),
RESERVE_09                   NUMBER   (9,0),
DSPNG_ACT1_TYPE              VARCHAR2 (1),
DSPNG_ACT2_TYPE              VARCHAR2 (2),
OLD_OLD_APPL_DIV             VARCHAR2 (1),
ES01_EQP_STD_CD              VARCHAR2 (3),
ES02_EQP_STD_CD              VARCHAR2 (3),
ES03_EQP_STD_CD              VARCHAR2 (3),
ES04_EQP_STD_CD              VARCHAR2 (3),
ES05_EQP_STD_CD              VARCHAR2 (3),
ES06_EQP_STD_CD              VARCHAR2 (3),
ES07_EQP_STD_CD              VARCHAR2 (3),
ES08_EQP_STD_CD              VARCHAR2 (3),
ES09_EQP_STD_CD              VARCHAR2 (3),
ES10_EQP_STD_CD              VARCHAR2 (3),
RU_RBL_DIV_CD                VARCHAR2 (2),
PRTU_RBL_DIV_CD              VARCHAR2 (2),
DU_RBL_DIV_CD                VARCHAR2 (2),
NAR_POI_STI_PSY_DRUG         VARCHAR2 (1),
TIME_ADD_DIV                 VARCHAR2 (1),
DSG_FRM                      VARCHAR2 (1),
RU_UPR_TIMES                 NUMBER   (2,0),
RU_UPR_TIMES_ERR             VARCHAR2 (1),
PRTU_UPR_TIMES               NUMBER   (2,0),
PRTU_UPR_TIMES_ERR           VARCHAR2 (1),
NOTE_ADD_CD                  VARCHAR2 (4),
NOTE_ADD_SERL_NO             VARCHAR2 (1),
LMT_AGE_LWR                  VARCHAR2 (2),
LMT_AGE_UPR                  VARCHAR2 (2),
PMC_DIV                      VARCHAR2 (1),
NOTIF_IDENT1_DIV             VARCHAR2 (1),
NOTIF_IDENT2_DIV             VARCHAR2 (1),
OS_OLD_SCORE_IDENT           VARCHAR2 (1),
OS_OLD_SCORE                 NUMBER   (9,2),
CHG_YMD                      VARCHAR2 (8),
ABO_YMD                      VARCHAR2 (8),
PBLCT_ODR_NO                 VARCHAR2 (9),
CD_LST_NO                    VARCHAR2 (10),
NOTIF_ASCT_NO                VARCHAR2 (10),
TNOV_ASCT                    VARCHAR2 (9),
INPUT_YMD                    VARCHAR2 (8),
APPL_YM                      VARCHAR2 (6),
MST_GEN                      VARCHAR2 (9) NOT NULL ENABLE,
    CONSTRAINT TNDS_M_DSPNG_ACT_PK PRIMARY KEY (MST_GEN,DSPNG_ACT_CD) USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 30
;
