CREATE TABLE TNDS_M_TREAT2
(
MDC_CD                       VARCHAR2 (2) NOT NULL ENABLE,
CLS_CD                       VARCHAR2 (4) NOT NULL ENABLE,
CRSPD_CD                     VARCHAR2 (1),
TREAT2_FLG                   VARCHAR2 (2),
TREAT_ETC1_NAME              NVARCHAR2(60),
TREAT_ETC1_CD                NVARCHAR2(10) NOT NULL ENABLE,
TREAT_ETC2_NAME              NVARCHAR2(60),
TREAT_ETC2_CD                NVARCHAR2(10),
CHG_DIV                      VARCHAR2 (1),
VALID_STR_YMD                VARCHAR2 (8),
VALID_END_YMD                VARCHAR2 (8),
UPD_YMD                      VARCHAR2 (8),
INPUT_YMD                    VARCHAR2 (8),
APPL_YM                      VARCHAR2 (6),
MST_GEN                      VARCHAR2 (9) NOT NULL ENABLE,
    CONSTRAINT TNDS_M_TREAT2_PK PRIMARY KEY (MST_GEN,MDC_CD,CLS_CD,TREAT_ETC1_CD) USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 30
;
