CREATE TABLE TNDS_M_SVRTY_SURG
(
MDC_CD                       VARCHAR2 (2) NOT NULL ENABLE,
CLS_CD                       VARCHAR2 (4) NOT NULL ENABLE,
CNDTN_DIV                    VARCHAR2 (1) NOT NULL ENABLE,
CNDTN_NAME                   NVARCHAR2(7),
SURG_CNDTN1_ONE_EYE          NVARCHAR2(8),
SURG_CNDTN1_ZERO             VARCHAR2 (1),
SURG_CNDTN2_BOTH_EYE         NVARCHAR2(4),
SURG_CNDTN2_ONE              VARCHAR2 (1),
CHG_DIV                      VARCHAR2 (1),
VALID_STR_YMD                VARCHAR2 (8),
VALID_END_YMD                VARCHAR2 (8),
UPD_YMD                      VARCHAR2 (8),
INPUT_YMD                    VARCHAR2 (8),
APPL_YM                      VARCHAR2 (6),
MST_GEN                      VARCHAR2 (9) NOT NULL ENABLE,
    CONSTRAINT TNDS_M_SVRTY_SURG_PK PRIMARY KEY (MST_GEN,MDC_CD,CLS_CD,CNDTN_DIV) USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 30
;
