CREATE TABLE TNDS_M_TOKKEN_ITEM
(
DIV_NO                       VARCHAR2 (5),
DIV_NAME                     NVARCHAR2(50),
TURN_NO                      NVARCHAR2(4),
ITEM_CD                      VARCHAR2 (20) NOT NULL ENABLE,
XML_DSP_NAME                 NVARCHAR2(50),
EXSR_GRP_IDENT               VARCHAR2 (20),
EXSR_GRP_RLTN_CD             VARCHAR2 (8),
SAME_SEX_ITEM_CD             VARCHAR2 (8),
SAME_SEX_ITEM_NAME           NVARCHAR2(50),
REMARK                       NVARCHAR2(80),
INPUT_YMD                    VARCHAR2 (8),
APPL_YM                      VARCHAR2 (6),
MST_GEN                      VARCHAR2 (9) NOT NULL ENABLE,
    CONSTRAINT TNDS_M_TOKKEN_ITEM_PK PRIMARY KEY (MST_GEN,ITEM_CD) USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 30
;
