CREATE TABLE TNDS_M_THOKEN_ITEM
(
ENTRY_NAME                   NVARCHAR2(20),
MHLW_DOC_NO                  VARCHAR2 (6),
XML_ITEM_CD                  VARCHAR2 (10) NOT NULL ENABLE,
ITEM_NAME                    NVARCHAR2(50),
RESERVE_01                   NVARCHAR2(80),
INPUT_YMD                    VARCHAR2 (8),
APPL_YM                      VARCHAR2 (6),
MST_GEN                      VARCHAR2 (9) NOT NULL ENABLE,
    CONSTRAINT TNDS_M_THOKEN_ITEM_PK PRIMARY KEY (MST_GEN,XML_ITEM_CD) USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 30
;
