CREATE TABLE TNDS_M_SCND_MEDI_AREA
(
EQP_TTL_NUM                  NUMBER   (4,0),
EQP_MNTL_HSPTL_NUM           NUMBER   (3,0),
EQP_GNRL_HSPTL_TTL_NUM       NUMBER   (4,0),
EQP_GNRL_HSPTL_HHRB_NUM      NUMBER   (4,0),
LCL_SPRT_MEDI_HSPTL_NUM      NUMBER   (3,0),
EMGCY_NOTIF_HSPTL_NUM        NUMBER   (4,0),
BED_TTL_NUM                  NUMBER   (7,0),
BED_MNTL_BED_NUM             NUMBER   (6,0),
BED_INFE_BED_NUM             NUMBER   (4,0),
BED_TB_BED_NUM               NUMBER   (4,0),
BED_RECU_BED_NUM             NUMBER   (6,0),
BED_GNRL_BED_NUM             NUMBER   (6,0),
LCL_SPRT_MEDI_BED_NUM        NUMBER   (6,0),
TDFK_CD                      VARCHAR2 (2),
TDFK_NAME                    NVARCHAR2(4),
CKTS_CD                      VARCHAR2 (5) NOT NULL ENABLE,
CKTS_NAME                    NVARCHAR2(38),
SCND_MEDI_AREA_CD            VARCHAR2 (4),
SCND_MEDI_AREA_NAME          NVARCHAR2(10),
INPUT_YMD                    VARCHAR2 (8),
APPL_YM                      VARCHAR2 (6),
MST_GEN                      VARCHAR2 (9) NOT NULL ENABLE,
    CONSTRAINT TNDS_M_SCND_MEDI_AREA_PK PRIMARY KEY (CKTS_CD,MST_GEN) USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 30
;
