CREATE TABLE TNDS_M_TOKKEN_ID3
(
ID1                          VARCHAR2 (64) NOT NULL ENABLE,
ID3                          VARCHAR2 (64),
INSURER_NO                   VARCHAR2 (8),
    CONSTRAINT TNDS_M_TOKKEN_ID3_PK PRIMARY KEY (ID1) USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 30
;
