CREATE TABLE TNDS_M_KO_FLG_CNG
(
DEFRAYER_NO                  VARCHAR2 (8) NOT NULL ENABLE,
PRAC_YM_FROM                 VARCHAR2 (5),
PRAC_YM_TO                   VARCHAR2 (5),
REQ_YM_FROM                  VARCHAR2 (5),
REQ_YM_TO                    VARCHAR2 (5),
    CONSTRAINT TNDS_M_KO_FLG_CNG_PK PRIMARY KEY (DEFRAYER_NO) USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 30
;
