
@ddl/08_NDB_MASTER/00_CREATE_TABLE_ALL.sql
@ddl/09_NDB_RECEIPT/00_CREATE_TABLE_ALL.sql
@ddl/10_NDB_TOKKEN_THOKEN/00_CREATE_TABLE_ALL.sql
@ddl/11_SONOTA/00_CREATE_TABLE_ALL.sql
@ddl/12_CB_MASTER/00_CREATE_TABLE_ALL.sql
@ddl/12_CB_MASTER/INSERT/ALL.sql
@ddl/12_CB_MASTER_VIEW/nengetsu/CREATE/00_CREATE_VIEW_ALL.sql
@ddl/13_CB_MOKUTEKIBETSU/00_CREATE_TABLE_ALL_TOKKEN_THOKEN.sql
@ddl/12_CB_MASTER_VIEW/nengetsu/REFRESH/00_REFRESH_ALL.sql
@ddl/13_CB_MOKUTEKIBETSU_VIEW/02_KOUHI_TANDOKU_DAISANSHA_RECEIPT/00_CREATE_VIEW_ALL.sql
@ddl/13_CB_MOKUTEKIBETSU_VIEW/12_KOUHI_TANDOKU_DAISANSHA_TOKKEN_THOKEN/00_CREATE_VIEW_ALL.sql
@ddl/13_CB_MOKUTEKIBETSU_VIEW/21_MOKUTEKIBETSU_DB/00_CREATE_VIEW_ALL.sql

exit;

