@sample/DEN/DEN_CO.sql
@sample/DEN/DEN_HO.sql
@sample/DEN/DEN_HS.sql
@sample/DEN/DEN_IR.sql
@sample/DEN/DEN_IY.sql
@sample/DEN/DEN_KH.sql
@sample/DEN/DEN_KO.sql
@sample/DEN/DEN_MN.sql
@sample/DEN/DEN_NI.sql
@sample/DEN/DEN_RE.sql
@sample/DEN/DEN_SI.sql
@sample/DEN/DEN_SI_WARD.sql
@sample/DEN/DEN_SJ.sql
@sample/DEN/DEN_SS.sql
@sample/DEN/DEN_TO.sql
@sample/DPC/DPC_BU.sql
@sample/DPC/DPC_CD.sql
@sample/DPC/DPC_CO.sql
@sample/DPC/DPC_GA.sql
@sample/DPC/DPC_GR.sql
@sample/DPC/DPC_GT.sql
@sample/DPC/DPC_HH.sql
@sample/DPC/DPC_HO.sql
@sample/DPC/DPC_IR.sql
@sample/DPC/DPC_IY.sql
@sample/DPC/DPC_KH.sql
@sample/DPC/DPC_KK.sql
@sample/DPC/DPC_KO.sql
@sample/DPC/DPC_MN.sql
@sample/DPC/DPC_NI.sql
@sample/DPC/DPC_RE.sql
@sample/DPC/DPC_SB.sql
@sample/DPC/DPC_SI.sql
@sample/DPC/DPC_SI_WARD.sql
@sample/DPC/DPC_SJ.sql
@sample/DPC/DPC_SK.sql
@sample/DPC/DPC_SY.sql
@sample/DPC/DPC_TI.sql
@sample/DPC/DPC_TO.sql
@sample/DPC/DPC_TR.sql
@sample/DPC/DPC_TS.sql
@sample/KENSHIN/TOKKEN_BASE.sql
@sample/KENSHIN/TOKKEN_DETAIL.sql
@sample/KENSHIN/TOKKEN_EXAM.sql
@sample/KENSHIN/TOKKEN_SEC.sql
@sample/MED/MED_CO.sql
@sample/MED/MED_GR.sql
@sample/MED/MED_HO.sql
@sample/MED/MED_IR.sql
@sample/MED/MED_IY.sql
@sample/MED/MED_KH.sql
@sample/MED/MED_KO.sql
@sample/MED/MED_MN.sql
@sample/MED/MED_NI.sql
@sample/MED/MED_RE.sql
@sample/MED/MED_SI.sql
@sample/MED/MED_SI_WARD.sql
@sample/MED/MED_SJ.sql
@sample/MED/MED_SY.sql
@sample/MED/MED_TI.sql
@sample/MED/MED_TO.sql
@sample/MED/MED_TR.sql
@sample/MED/MED_TS.sql
@sample/PHA/PHA_CO.sql
@sample/PHA/PHA_CZ.sql
@sample/PHA/PHA_HO.sql
@sample/PHA/PHA_IY.sql
@sample/PHA/PHA_KH.sql
@sample/PHA/PHA_KI.sql
@sample/PHA/PHA_KO.sql
@sample/PHA/PHA_MN.sql
@sample/PHA/PHA_RE.sql
@sample/PHA/PHA_SH.sql
@sample/PHA/PHA_ST.sql
@sample/PHA/PHA_TK.sql
@sample/PHA/PHA_TO.sql
@sample/PHA/PHA_YK.sql
@sample/SHIDO/THOKEN_BASE.sql
@sample/SHIDO/THOKEN_ENTRY.sql
@sample/SHIDO/THOKEN_FACE.sql
@sample/SHIDO/THOKEN_RESULT.sql
@sample/SHIDO/THOKEN_SEC.sql
exit;
