CREATE VIEW CMDV_T_MED_TO AS
  SELECT /*+ USE_HASH_AGGREGATION */
    MTO.SEQ2_NO
  , MTO.SERL_NO
  , MTO.AFT_SPLMT_PRAC_IDENT
  , SUM(MTO.SCORE)             AS SCORE
  , SUM(MTO.AFT_SPLMT_SCORE)   AS AFT_SPLMT_SCORE
  , SUM(MTO.TIMES)             AS TIMES
  , SUM(MTO.AFT_SPLMT_TIMES)   AS AFT_SPLMT_TIMES
  , SUM(MTO.DAYS01_INFO)       AS DAYS01_INFO
  , SUM(MTO.DAYS02_INFO)       AS DAYS02_INFO
  , SUM(MTO.DAYS03_INFO)       AS DAYS03_INFO
  , SUM(MTO.DAYS04_INFO)       AS DAYS04_INFO
  , SUM(MTO.DAYS05_INFO)       AS DAYS05_INFO
  , SUM(MTO.DAYS06_INFO)       AS DAYS06_INFO
  , SUM(MTO.DAYS07_INFO)       AS DAYS07_INFO
  , SUM(MTO.DAYS08_INFO)       AS DAYS08_INFO
  , SUM(MTO.DAYS09_INFO)       AS DAYS09_INFO
  , SUM(MTO.DAYS10_INFO)       AS DAYS10_INFO
  , SUM(MTO.DAYS11_INFO)       AS DAYS11_INFO
  , SUM(MTO.DAYS12_INFO)       AS DAYS12_INFO
  , SUM(MTO.DAYS13_INFO)       AS DAYS13_INFO
  , SUM(MTO.DAYS14_INFO)       AS DAYS14_INFO
  , SUM(MTO.DAYS15_INFO)       AS DAYS15_INFO
  , SUM(MTO.DAYS16_INFO)       AS DAYS16_INFO
  , SUM(MTO.DAYS17_INFO)       AS DAYS17_INFO
  , SUM(MTO.DAYS18_INFO)       AS DAYS18_INFO
  , SUM(MTO.DAYS19_INFO)       AS DAYS19_INFO
  , SUM(MTO.DAYS20_INFO)       AS DAYS20_INFO
  , SUM(MTO.DAYS21_INFO)       AS DAYS21_INFO
  , SUM(MTO.DAYS22_INFO)       AS DAYS22_INFO
  , SUM(MTO.DAYS23_INFO)       AS DAYS23_INFO
  , SUM(MTO.DAYS24_INFO)       AS DAYS24_INFO
  , SUM(MTO.DAYS25_INFO)       AS DAYS25_INFO
  , SUM(MTO.DAYS26_INFO)       AS DAYS26_INFO
  , SUM(MTO.DAYS27_INFO)       AS DAYS27_INFO
  , SUM(MTO.DAYS28_INFO)       AS DAYS28_INFO
  , SUM(MTO.DAYS29_INFO)       AS DAYS29_INFO
  , SUM(MTO.DAYS30_INFO)       AS DAYS30_INFO
  , SUM(MTO.DAYS31_INFO)       AS DAYS31_INFO
  , MTO.PRAC_YM                AS PRAC_YM
  FROM
    TNDS_T_RCP_MED_TO MTO
  WHERE
    MTO.KO_FLG IN (0,2)
  GROUP BY
    MTO.SEQ2_NO
  , MTO.SERL_NO
  , MTO.AFT_SPLMT_PRAC_IDENT
  , MTO.PRAC_YM
WITH READ ONLY
;
