CREATE VIEW CMDV_T_DPC_SI AS
  SELECT /*+ USE_HASH_AGGREGATION */
    SI.SEQ2_NO
  , SI.SERL_NO
  , SI.AFT_SPLMT_PRAC_IDENT
  , SUM(SI.QNT_DAT)           AS QNT_DAT
  , SUM(SI.SCORE)             AS SCORE
  , SUM(SI.AFT_SPLMT_SCORE)   AS AFT_SPLMT_SCORE
  , SUM(SI.TIMES)             AS TIMES
  , SUM(SI.AFT_SPLMT_TIMES)   AS AFT_SPLMT_TIMES
  , SUM(SI.DAYS01_INFO)       AS DAYS01_INFO
  , SUM(SI.DAYS02_INFO)       AS DAYS02_INFO
  , SUM(SI.DAYS03_INFO)       AS DAYS03_INFO
  , SUM(SI.DAYS04_INFO)       AS DAYS04_INFO
  , SUM(SI.DAYS05_INFO)       AS DAYS05_INFO
  , SUM(SI.DAYS06_INFO)       AS DAYS06_INFO
  , SUM(SI.DAYS07_INFO)       AS DAYS07_INFO
  , SUM(SI.DAYS08_INFO)       AS DAYS08_INFO
  , SUM(SI.DAYS09_INFO)       AS DAYS09_INFO
  , SUM(SI.DAYS10_INFO)       AS DAYS10_INFO
  , SUM(SI.DAYS11_INFO)       AS DAYS11_INFO
  , SUM(SI.DAYS12_INFO)       AS DAYS12_INFO
  , SUM(SI.DAYS13_INFO)       AS DAYS13_INFO
  , SUM(SI.DAYS14_INFO)       AS DAYS14_INFO
  , SUM(SI.DAYS15_INFO)       AS DAYS15_INFO
  , SUM(SI.DAYS16_INFO)       AS DAYS16_INFO
  , SUM(SI.DAYS17_INFO)       AS DAYS17_INFO
  , SUM(SI.DAYS18_INFO)       AS DAYS18_INFO
  , SUM(SI.DAYS19_INFO)       AS DAYS19_INFO
  , SUM(SI.DAYS20_INFO)       AS DAYS20_INFO
  , SUM(SI.DAYS21_INFO)       AS DAYS21_INFO
  , SUM(SI.DAYS22_INFO)       AS DAYS22_INFO
  , SUM(SI.DAYS23_INFO)       AS DAYS23_INFO
  , SUM(SI.DAYS24_INFO)       AS DAYS24_INFO
  , SUM(SI.DAYS25_INFO)       AS DAYS25_INFO
  , SUM(SI.DAYS26_INFO)       AS DAYS26_INFO
  , SUM(SI.DAYS27_INFO)       AS DAYS27_INFO
  , SUM(SI.DAYS28_INFO)       AS DAYS28_INFO
  , SUM(SI.DAYS29_INFO)       AS DAYS29_INFO
  , SUM(SI.DAYS30_INFO)       AS DAYS30_INFO
  , SUM(SI.DAYS31_INFO)       AS DAYS31_INFO
  , SI.PRAC_YM                AS PRAC_YM
  FROM
    TNDS_T_RCP_DPC_SI SI
  WHERE
    SI.KO_FLG IN (0,2)
  GROUP BY
    SI.SEQ2_NO
  , SI.SERL_NO
  , SI.AFT_SPLMT_PRAC_IDENT
  , SI.PRAC_YM
WITH READ ONLY
;
