CREATE VIEW CMDV_T_DPC_TO AS
  SELECT /*+ USE_HASH_AGGREGATION */
    DPTO.SEQ2_NO
  , DPTO.SERL_NO
  , DPTO.AFT_SPLMT_PRAC_IDENT
  , SUM(DPTO.SCORE)             AS SCORE
  , SUM(DPTO.AFT_SPLMT_SCORE)   AS AFT_SPLMT_SCORE
  , SUM(DPTO.TIMES)             AS TIMES
  , SUM(DPTO.AFT_SPLMT_TIMES)   AS AFT_SPLMT_TIMES
  , SUM(DPTO.DAYS01_INFO)       AS DAYS01_INFO
  , SUM(DPTO.DAYS02_INFO)       AS DAYS02_INFO
  , SUM(DPTO.DAYS03_INFO)       AS DAYS03_INFO
  , SUM(DPTO.DAYS04_INFO)       AS DAYS04_INFO
  , SUM(DPTO.DAYS05_INFO)       AS DAYS05_INFO
  , SUM(DPTO.DAYS06_INFO)       AS DAYS06_INFO
  , SUM(DPTO.DAYS07_INFO)       AS DAYS07_INFO
  , SUM(DPTO.DAYS08_INFO)       AS DAYS08_INFO
  , SUM(DPTO.DAYS09_INFO)       AS DAYS09_INFO
  , SUM(DPTO.DAYS10_INFO)       AS DAYS10_INFO
  , SUM(DPTO.DAYS11_INFO)       AS DAYS11_INFO
  , SUM(DPTO.DAYS12_INFO)       AS DAYS12_INFO
  , SUM(DPTO.DAYS13_INFO)       AS DAYS13_INFO
  , SUM(DPTO.DAYS14_INFO)       AS DAYS14_INFO
  , SUM(DPTO.DAYS15_INFO)       AS DAYS15_INFO
  , SUM(DPTO.DAYS16_INFO)       AS DAYS16_INFO
  , SUM(DPTO.DAYS17_INFO)       AS DAYS17_INFO
  , SUM(DPTO.DAYS18_INFO)       AS DAYS18_INFO
  , SUM(DPTO.DAYS19_INFO)       AS DAYS19_INFO
  , SUM(DPTO.DAYS20_INFO)       AS DAYS20_INFO
  , SUM(DPTO.DAYS21_INFO)       AS DAYS21_INFO
  , SUM(DPTO.DAYS22_INFO)       AS DAYS22_INFO
  , SUM(DPTO.DAYS23_INFO)       AS DAYS23_INFO
  , SUM(DPTO.DAYS24_INFO)       AS DAYS24_INFO
  , SUM(DPTO.DAYS25_INFO)       AS DAYS25_INFO
  , SUM(DPTO.DAYS26_INFO)       AS DAYS26_INFO
  , SUM(DPTO.DAYS27_INFO)       AS DAYS27_INFO
  , SUM(DPTO.DAYS28_INFO)       AS DAYS28_INFO
  , SUM(DPTO.DAYS29_INFO)       AS DAYS29_INFO
  , SUM(DPTO.DAYS30_INFO)       AS DAYS30_INFO
  , SUM(DPTO.DAYS31_INFO)       AS DAYS31_INFO
  , DPTO.PRAC_YM                AS PRAC_YM
  FROM
    TNDS_T_RCP_DPC_TO DPTO
  WHERE
    DPTO.KO_FLG IN (0,2)
  GROUP BY
    DPTO.SEQ2_NO
  , DPTO.SERL_NO
  , DPTO.AFT_SPLMT_PRAC_IDENT
  , DPTO.PRAC_YM
WITH READ ONLY
;
