CREATE VIEW CMDV_T_DEN_SS AS
  SELECT /*+ USE_HASH_AGGREGATION */
    SS.SEQ2_NO
  , SS.SERL_NO
  , SS.AFT_SPLMT_PRAC_IDENT
  , SUM(SS.PRAC_ACT_AMNT1_DAT)   AS PRAC_ACT_AMNT1_DAT
  , SUM(SS.PRAC_ACT_AMNT2_DAT)   AS PRAC_ACT_AMNT2_DAT
  , SUM(SS.ADD01_AMNT_DAT)       AS ADD01_AMNT_DAT
  , SUM(SS.ADD02_AMNT_DAT)       AS ADD02_AMNT_DAT
  , SUM(SS.ADD03_AMNT_DAT)       AS ADD03_AMNT_DAT
  , SUM(SS.ADD04_AMNT_DAT)       AS ADD04_AMNT_DAT
  , SUM(SS.ADD05_AMNT_DAT)       AS ADD05_AMNT_DAT
  , SUM(SS.ADD06_AMNT_DAT)       AS ADD06_AMNT_DAT
  , SUM(SS.ADD07_AMNT_DAT)       AS ADD07_AMNT_DAT
  , SUM(SS.ADD08_AMNT_DAT)       AS ADD08_AMNT_DAT
  , SUM(SS.ADD09_AMNT_DAT)       AS ADD09_AMNT_DAT
  , SUM(SS.ADD10_AMNT_DAT)       AS ADD10_AMNT_DAT
  , SUM(SS.ADD11_AMNT_DAT)       AS ADD11_AMNT_DAT
  , SUM(SS.ADD12_AMNT_DAT)       AS ADD12_AMNT_DAT
  , SUM(SS.ADD13_AMNT_DAT)       AS ADD13_AMNT_DAT
  , SUM(SS.ADD14_AMNT_DAT)       AS ADD14_AMNT_DAT
  , SUM(SS.ADD15_AMNT_DAT)       AS ADD15_AMNT_DAT
  , SUM(SS.ADD16_AMNT_DAT)       AS ADD16_AMNT_DAT
  , SUM(SS.ADD17_AMNT_DAT)       AS ADD17_AMNT_DAT
  , SUM(SS.ADD18_AMNT_DAT)       AS ADD18_AMNT_DAT
  , SUM(SS.ADD19_AMNT_DAT)       AS ADD19_AMNT_DAT
  , SUM(SS.ADD20_AMNT_DAT)       AS ADD20_AMNT_DAT
  , SUM(SS.ADD21_AMNT_DAT)       AS ADD21_AMNT_DAT
  , SUM(SS.ADD22_AMNT_DAT)       AS ADD22_AMNT_DAT
  , SUM(SS.ADD23_AMNT_DAT)       AS ADD23_AMNT_DAT
  , SUM(SS.ADD24_AMNT_DAT)       AS ADD24_AMNT_DAT
  , SUM(SS.ADD25_AMNT_DAT)       AS ADD25_AMNT_DAT
  , SUM(SS.ADD26_AMNT_DAT)       AS ADD26_AMNT_DAT
  , SUM(SS.ADD27_AMNT_DAT)       AS ADD27_AMNT_DAT
  , SUM(SS.ADD28_AMNT_DAT)       AS ADD28_AMNT_DAT
  , SUM(SS.ADD29_AMNT_DAT)       AS ADD29_AMNT_DAT
  , SUM(SS.ADD30_AMNT_DAT)       AS ADD30_AMNT_DAT
  , SUM(SS.ADD31_AMNT_DAT)       AS ADD31_AMNT_DAT
  , SUM(SS.ADD32_AMNT_DAT)       AS ADD32_AMNT_DAT
  , SUM(SS.ADD33_AMNT_DAT)       AS ADD33_AMNT_DAT
  , SUM(SS.ADD34_AMNT_DAT)       AS ADD34_AMNT_DAT
  , SUM(SS.ADD35_AMNT_DAT)       AS ADD35_AMNT_DAT
  , SUM(SS.SCORE)                AS SCORE
  , SUM(SS.AFT_SPLMT_SCORE)      AS AFT_SPLMT_SCORE
  , SUM(SS.TIMES)                AS TIMES
  , SUM(SS.DAYS01_INFO)          AS DAYS01_INFO
  , SUM(SS.DAYS02_INFO)          AS DAYS02_INFO
  , SUM(SS.DAYS03_INFO)          AS DAYS03_INFO
  , SUM(SS.DAYS04_INFO)          AS DAYS04_INFO
  , SUM(SS.DAYS05_INFO)          AS DAYS05_INFO
  , SUM(SS.DAYS06_INFO)          AS DAYS06_INFO
  , SUM(SS.DAYS07_INFO)          AS DAYS07_INFO
  , SUM(SS.DAYS08_INFO)          AS DAYS08_INFO
  , SUM(SS.DAYS09_INFO)          AS DAYS09_INFO
  , SUM(SS.DAYS10_INFO)          AS DAYS10_INFO
  , SUM(SS.DAYS11_INFO)          AS DAYS11_INFO
  , SUM(SS.DAYS12_INFO)          AS DAYS12_INFO
  , SUM(SS.DAYS13_INFO)          AS DAYS13_INFO
  , SUM(SS.DAYS14_INFO)          AS DAYS14_INFO
  , SUM(SS.DAYS15_INFO)          AS DAYS15_INFO
  , SUM(SS.DAYS16_INFO)          AS DAYS16_INFO
  , SUM(SS.DAYS17_INFO)          AS DAYS17_INFO
  , SUM(SS.DAYS18_INFO)          AS DAYS18_INFO
  , SUM(SS.DAYS19_INFO)          AS DAYS19_INFO
  , SUM(SS.DAYS20_INFO)          AS DAYS20_INFO
  , SUM(SS.DAYS21_INFO)          AS DAYS21_INFO
  , SUM(SS.DAYS22_INFO)          AS DAYS22_INFO
  , SUM(SS.DAYS23_INFO)          AS DAYS23_INFO
  , SUM(SS.DAYS24_INFO)          AS DAYS24_INFO
  , SUM(SS.DAYS25_INFO)          AS DAYS25_INFO
  , SUM(SS.DAYS26_INFO)          AS DAYS26_INFO
  , SUM(SS.DAYS27_INFO)          AS DAYS27_INFO
  , SUM(SS.DAYS28_INFO)          AS DAYS28_INFO
  , SUM(SS.DAYS29_INFO)          AS DAYS29_INFO
  , SUM(SS.DAYS30_INFO)          AS DAYS30_INFO
  , SUM(SS.DAYS31_INFO)          AS DAYS31_INFO
  , SS.PRAC_YM                   AS PRAC_YM
  FROM
    TNDS_T_RCP_DEN_SS SS
  WHERE
    SS.KO_FLG IN (0,2)
  GROUP BY
    SS.SEQ2_NO
  , SS.SERL_NO
  , SS.AFT_SPLMT_PRAC_IDENT
  , SS.PRAC_YM
WITH READ ONLY
;
