CREATE VIEW CMDV_T_DEN_TO AS
  SELECT /*+ USE_HASH_AGGREGATION */
    DTO.SEQ2_NO
  , DTO.SERL_NO
  , DTO.AFT_SPLMT_PRAC_IDENT
  , SUM(DTO.SCORE)             AS SCORE
  , SUM(DTO.AFT_SPLMT_SCORE)   AS AFT_SPLMT_SCORE
  , SUM(DTO.TIMES)             AS TIMES
  , SUM(DTO.AFT_SPLMT_TIMES)   AS AFT_SPLMT_TIMES
  , SUM(DTO.DAYS01_INFO)       AS DAYS01_INFO
  , SUM(DTO.DAYS02_INFO)       AS DAYS02_INFO
  , SUM(DTO.DAYS03_INFO)       AS DAYS03_INFO
  , SUM(DTO.DAYS04_INFO)       AS DAYS04_INFO
  , SUM(DTO.DAYS05_INFO)       AS DAYS05_INFO
  , SUM(DTO.DAYS06_INFO)       AS DAYS06_INFO
  , SUM(DTO.DAYS07_INFO)       AS DAYS07_INFO
  , SUM(DTO.DAYS08_INFO)       AS DAYS08_INFO
  , SUM(DTO.DAYS09_INFO)       AS DAYS09_INFO
  , SUM(DTO.DAYS10_INFO)       AS DAYS10_INFO
  , SUM(DTO.DAYS11_INFO)       AS DAYS11_INFO
  , SUM(DTO.DAYS12_INFO)       AS DAYS12_INFO
  , SUM(DTO.DAYS13_INFO)       AS DAYS13_INFO
  , SUM(DTO.DAYS14_INFO)       AS DAYS14_INFO
  , SUM(DTO.DAYS15_INFO)       AS DAYS15_INFO
  , SUM(DTO.DAYS16_INFO)       AS DAYS16_INFO
  , SUM(DTO.DAYS17_INFO)       AS DAYS17_INFO
  , SUM(DTO.DAYS18_INFO)       AS DAYS18_INFO
  , SUM(DTO.DAYS19_INFO)       AS DAYS19_INFO
  , SUM(DTO.DAYS20_INFO)       AS DAYS20_INFO
  , SUM(DTO.DAYS21_INFO)       AS DAYS21_INFO
  , SUM(DTO.DAYS22_INFO)       AS DAYS22_INFO
  , SUM(DTO.DAYS23_INFO)       AS DAYS23_INFO
  , SUM(DTO.DAYS24_INFO)       AS DAYS24_INFO
  , SUM(DTO.DAYS25_INFO)       AS DAYS25_INFO
  , SUM(DTO.DAYS26_INFO)       AS DAYS26_INFO
  , SUM(DTO.DAYS27_INFO)       AS DAYS27_INFO
  , SUM(DTO.DAYS28_INFO)       AS DAYS28_INFO
  , SUM(DTO.DAYS29_INFO)       AS DAYS29_INFO
  , SUM(DTO.DAYS30_INFO)       AS DAYS30_INFO
  , SUM(DTO.DAYS31_INFO)       AS DAYS31_INFO
  , DTO.PRAC_YM                AS PRAC_YM
  FROM
    TNDS_T_RCP_DEN_TO DTO
  WHERE
    DTO.KO_FLG IN (0,2)
  GROUP BY
    DTO.SEQ2_NO
  , DTO.SERL_NO
  , DTO.AFT_SPLMT_PRAC_IDENT
  , DTO.PRAC_YM
WITH READ ONLY
;
