CREATE VIEW CMDV_T_PHA_CZ AS
  SELECT /*+ USE_HASH_AGGREGATION */
    CZ.SEQ2_NO
  , SUM(CZ.PRSPT_RCPTN_TIME)  AS PRSPT_RCPTN_TIME
  , SUM(CZ.DSPNG_AMNT)         AS DSPNG_AMNT
  , SUM(CZ.DSC_SCORE)          AS DSC_SCORE
  , SUM(CZ.DRC_SCORE)          AS DRC_SCORE
  , SUM(CZ.ADC01_SCORE)        AS ADC01_SCORE
  , SUM(CZ.ADC02_SCORE)        AS ADC02_SCORE
  , SUM(CZ.ADC03_SCORE)        AS ADC03_SCORE
  , SUM(CZ.ADC04_SCORE)        AS ADC04_SCORE
  , SUM(CZ.ADC05_SCORE)        AS ADC05_SCORE
  , SUM(CZ.ADC06_SCORE)        AS ADC06_SCORE
  , SUM(CZ.ADC07_SCORE)        AS ADC07_SCORE
  , SUM(CZ.ADC08_SCORE)        AS ADC08_SCORE
  , SUM(CZ.ADC09_SCORE)        AS ADC09_SCORE
  , SUM(CZ.ADC10_SCORE)        AS ADC10_SCORE
  , CZ.PRAC_YM                 AS PRAC_YM
  FROM
    TNDS_T_RCP_PHA_CZ CZ
  WHERE
    CZ.KO_FLG IN (0,2)
  GROUP BY
    CZ.SEQ2_NO
   ,CZ.PRAC_YM
WITH READ ONLY
;
