CREATE VIEW CMDV_T_PHA_KI AS
  SELECT /*+ USE_HASH_AGGREGATION */
    KI.SEQ2_NO
  , SUM(KI.PRSPT_RCPTN_TIME)  AS PRSPT_RCPTN_TIME
  , SUM(KI.DBC_SCORE)          AS DBC_SCORE
  , SUM(KI.PMC01_TIMES)        AS PMC01_TIMES
  , SUM(KI.PMC01_SCORE)        AS PMC01_SCORE
  , SUM(KI.PMC02_TIMES)        AS PMC02_TIMES
  , SUM(KI.PMC02_SCORE)        AS PMC02_SCORE
  , SUM(KI.PMC03_TIMES)        AS PMC03_TIMES
  , SUM(KI.PMC03_SCORE)        AS PMC03_SCORE
  , SUM(KI.PMC04_TIMES)        AS PMC04_TIMES
  , SUM(KI.PMC04_SCORE)        AS PMC04_SCORE
  , SUM(KI.PMC05_TIMES)        AS PMC05_TIMES
  , SUM(KI.PMC05_SCORE)        AS PMC05_SCORE
  , SUM(KI.PMC06_TIMES)        AS PMC06_TIMES
  , SUM(KI.PMC06_SCORE)        AS PMC06_SCORE
  , SUM(KI.PMC07_TIMES)        AS PMC07_TIMES
  , SUM(KI.PMC07_SCORE)        AS PMC07_SCORE
  , SUM(KI.PMC08_TIMES)        AS PMC08_TIMES
  , SUM(KI.PMC08_SCORE)        AS PMC08_SCORE
  , SUM(KI.PMC09_TIMES)        AS PMC09_TIMES
  , SUM(KI.PMC09_SCORE)        AS PMC09_SCORE
  , SUM(KI.PMC10_TIMES)        AS PMC10_TIMES
  , SUM(KI.PMC10_SCORE)        AS PMC10_SCORE
  , SUM(KI.PMC11_TIMES)        AS PMC11_TIMES
  , SUM(KI.PMC11_SCORE)        AS PMC11_SCORE
  , SUM(KI.PMC12_TIMES)        AS PMC12_TIMES
  , SUM(KI.PMC12_SCORE)        AS PMC12_SCORE
  , SUM(KI.SPMC01_TIMES)       AS SPMC01_TIMES
  , SUM(KI.SPMC01_SCORE)       AS SPMC01_SCORE
  , SUM(KI.SPMC02_TIMES)       AS SPMC02_TIMES
  , SUM(KI.SPMC02_SCORE)       AS SPMC02_SCORE
  , SUM(KI.SPMC03_TIMES)       AS SPMC03_TIMES
  , SUM(KI.SPMC03_SCORE)       AS SPMC03_SCORE
  , SUM(KI.DBA01_TIMES)        AS DBA01_TIMES
  , SUM(KI.DBA01_SCORE)        AS DBA01_SCORE
  , SUM(KI.DBA02_TIMES)        AS DBA02_TIMES
  , SUM(KI.DBA02_SCORE)        AS DBA02_SCORE
  , SUM(KI.DBA03_TIMES)        AS DBA03_TIMES
  , SUM(KI.DBA03_SCORE)        AS DBA03_SCORE
  , SUM(KI.DBA04_TIMES)        AS DBA04_TIMES
  , SUM(KI.DBA04_SCORE)        AS DBA04_SCORE
  , KI.PRAC_YM                 AS PRAC_YM
  FROM
    TNDS_T_RCP_PHA_KI KI
  WHERE
    KI.KO_FLG IN (0,2)
  GROUP BY
    KI.SEQ2_NO
   ,KI.PRAC_YM
WITH READ ONLY
;
