CREATE TABLE TNDS_T_RCP_PHA_CZ
(
SEQ1_NO                      VARCHAR2 (10) NOT NULL ENABLE,
SEQ2_NO                      VARCHAR2 (51) NOT NULL ENABLE,
VLD_FLG                      NUMBER   (1,0),
KO_FLG                       NUMBER   (1,0),
REC_IDENT_INFO               VARCHAR2 (2),
PRSPT_YMD                    VARCHAR2 (7),
DSPNG_YMD                    VARCHAR2 (7),
PRSPT_RCPTN_TIME             NUMBER   (2,0),
DSPNG_AMNT                   NUMBER   (3,0),
DSC_BURD_DIV                 VARCHAR2 (1),
DSC_CALC_DIV                 VARCHAR2 (1),
DSC_CALC_NO                  VARCHAR2 (2),
DSC_CD                       VARCHAR2 (9),
DSC_SCORE                    NUMBER   (4,0),
DVD_DVSN_DIV                 NUMBER   (2,0),
DVD_LAST_AMNT                NUMBER   (3,0),
DRC_SCORE                    NUMBER   (7,0),
RESERVE_01                   NUMBER   (7,0),
ADC01_BURD_DIV               VARCHAR2 (1),
ADC01_CD                     VARCHAR2 (9),
ADC01_SCORE                  NUMBER   (4,0),
ADC02_BURD_DIV               VARCHAR2 (1),
ADC02_CD                     VARCHAR2 (9),
ADC02_SCORE                  NUMBER   (4,0),
ADC03_BURD_DIV               VARCHAR2 (1),
ADC03_CD                     VARCHAR2 (9),
ADC03_SCORE                  NUMBER   (4,0),
ADC04_BURD_DIV               VARCHAR2 (1),
ADC04_CD                     VARCHAR2 (9),
ADC04_SCORE                  NUMBER   (4,0),
ADC05_BURD_DIV               VARCHAR2 (1),
ADC05_CD                     VARCHAR2 (9),
ADC05_SCORE                  NUMBER   (4,0),
ADC06_BURD_DIV               VARCHAR2 (1),
ADC06_CD                     VARCHAR2 (9),
ADC06_SCORE                  NUMBER   (4,0),
ADC07_BURD_DIV               VARCHAR2 (1),
ADC07_CD                     VARCHAR2 (9),
ADC07_SCORE                  NUMBER   (4,0),
ADC08_BURD_DIV               VARCHAR2 (1),
ADC08_CD                     VARCHAR2 (9),
ADC08_SCORE                  NUMBER   (4,0),
ADC09_BURD_DIV               VARCHAR2 (1),
ADC09_CD                     VARCHAR2 (9),
ADC09_SCORE                  NUMBER   (4,0),
ADC10_BURD_DIV               VARCHAR2 (1),
ADC10_CD                     VARCHAR2 (9),
ADC10_SCORE                  NUMBER   (4,0),
PKG_DAYS                     NUMBER   (3,0),
DVSN_DSPNG_TYPE              VARCHAR2 (1),
LAST_PKG_DAYS                NUMBER   (3,0),
DIV_DISPENSATION_CD          VARCHAR2 (9),
DIV_DISPENSATION_DIV         VARCHAR2 (2),
DIV_TARGET_DISP_QUANTITY     NUMBER   (3,0),
PACKAGE_DIV_NUM_DAYS         NUMBER   (3,0),
INCLUSION_MANAGEMENT_CHARGES VARCHAR2 (2),
PRE_RECEPTION_OTHER_MED      VARCHAR2 (2),
PRSPT_NO                     NUMBER   (5,0),
PRSPT_SUB_NO                 NUMBER   (5,0),
PRAC_YM                      VARCHAR2 (5),
INPUT_YM                     VARCHAR2 (6)
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 30
;
