CREATE MATERIALIZED VIEW CMDS_M_PHA_CLA parallel 96 nologging
AS
select distinct
SEIREKI,
SEIREKI_NAME,
WAREKI,
WAREKI_NAME
from TNDS_T_TRANS_JC_YEAR
INNER JOIN TNDS_T_RCP_PHA_YK
ON
TNDS_T_TRANS_JC_YEAR.WAREKI = TNDS_T_RCP_PHA_YK.REQ_YM
order by SEIREKI DESC
;
