CREATE MATERIALIZED VIEW CMDS_M_MED_PRA parallel 96 nologging
AS
select distinct
SEIREKI,
SEIREKI_NAME,
WAREKI,
WAREKI_NAME
from TNDS_T_TRANS_JC_YEAR
INNER JOIN TNDS_T_RCP_MED_MN
ON
TNDS_T_TRANS_JC_YEAR.WAREKI = TNDS_T_RCP_MED_MN.PRAC_YM
order by SEIREKI  DESC
;
