CREATE TABLE "CMDS_M_RCP_CLS_PHA"
(
"RCP_CLS"                      VARCHAR2 (4) NOT NULL ENABLE,
"RCP_CLS_NAME"                 NVARCHAR2(100),
    CONSTRAINT "CMDS_M_RCP_CLS_PHA_PK" PRIMARY KEY ("RCP_CLS") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
