CREATE TABLE "CMDS_M_TDFK"
(
"TDFK"                         VARCHAR2 (2) NOT NULL ENABLE,
"TDFK_NAME"                    NVARCHAR2(10),
    CONSTRAINT "CMDS_M_TDFK_PK" PRIMARY KEY ("TDFK") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
