CREATE TABLE "CMDS_M_SEX_DIV"
(
"SEX_DIV"                      VARCHAR2 (1) NOT NULL ENABLE,
"SEX_DIV_NAME"                 NVARCHAR2(3),
    CONSTRAINT "CMDS_M_SEX_DIV_PK" PRIMARY KEY ("SEX_DIV") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
