CREATE TABLE "CMDS_M_RCP_IMPTT_NOTI"
(
"RCPT_IMPTT_NOTI_CD"           VARCHAR2 (2) NOT NULL ENABLE,
"RCPT_IMPTT_NOTI"              NVARCHAR2(10),
    CONSTRAINT "CMDS_M_RCP_IMPTT_NOTI_PK" PRIMARY KEY ("RCPT_IMPTT_NOTI_CD") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
