CREATE TABLE "CMDS_M_PRAC"
(
"PRAC_NAME"                    VARCHAR2 (2) NOT NULL ENABLE,
"PRAC_NAME_NAME"               NVARCHAR2(40),
    CONSTRAINT "CMDS_M_PRAC_PK" PRIMARY KEY ("PRAC_NAME") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
