CREATE TABLE "CMDS_M_PRAC_IDENT_DEN"
(
"PRAC_IDENT"                   VARCHAR2 (2) NOT NULL ENABLE,
"PRAC_IDENT_NAME"              NVARCHAR2(40),
    CONSTRAINT "CMDS_M_PRAC_IDENT_DEN_PK" PRIMARY KEY ("PRAC_IDENT") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
