CREATE TABLE "CMDS_M_DSG_FRM"
(
"DSG_FRM_CD"                   VARCHAR2 (1) NOT NULL ENABLE,
"DSG_FRM_NAME"                 NVARCHAR2(5),
    CONSTRAINT "CMDS_M_DSG_FRM_PK" PRIMARY KEY ("DSG_FRM_CD") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
