CREATE TABLE "CMDS_M_RCP_GNRLZ_DIV"
(
"RCPT_GNRLZ_DIV"               VARCHAR2 (1) NOT NULL ENABLE,
"RCPT_GNRLZ_DIV_NAME"          NVARCHAR2(20),
    CONSTRAINT "CMDS_M_RCP_GNRLZ_DIV_PK" PRIMARY KEY ("RCPT_GNRLZ_DIV") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
