CREATE TABLE "CMDS_M_REASON_DUTY"
(
"REASON_DUTY"                  VARCHAR2 (1) NOT NULL ENABLE,
"REASON_DUTY_NAME"             NVARCHAR2(20),
    CONSTRAINT "CMDS_M_REASON_DUTY_PK" PRIMARY KEY ("REASON_DUTY") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
