CREATE TABLE "CMDS_M_STAND_BURD_DIV"
(
"STAND_BURD_DIV"               VARCHAR2 (1) NOT NULL ENABLE,
"STAND_BURD_DIV_NAME"          NVARCHAR2(50),
    CONSTRAINT "CMDS_M_STAND_BURD_DIV_PK" PRIMARY KEY ("STAND_BURD_DIV") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
