CREATE TABLE "CMDS_M_OUTCM_DIV"
(
"OUTCM_DIV"                    VARCHAR2 (1) NOT NULL ENABLE,
"OUTCM_DIV_NAME"               NVARCHAR2(20),
    CONSTRAINT "CMDS_M_OUTCM_DIV_PK" PRIMARY KEY ("OUTCM_DIV") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
