CREATE TABLE "CMDS_M_SPCFC_DISE"
(
"SPCFC_DISE"                   VARCHAR2 (3) NOT NULL ENABLE,
"SPCFC_NAME"                   NVARCHAR2(14),
    CONSTRAINT "CMDS_M_SPCFC_DISE_PK" PRIMARY KEY ("SPCFC_DISE") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
