CREATE TABLE "CMDS_M_HOSTZ_DIV"
(
"HOSTZ_DIV"                    VARCHAR2 (1) NOT NULL ENABLE,
"HOSTZ_DIV_NAME"               NVARCHAR2(15),
    CONSTRAINT "CMDS_M_HOSTZ_DIV_PK" PRIMARY KEY ("HOSTZ_DIV") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
