CREATE TABLE "CMDS_M_NUM_INS_NUM"
(
"NUM_INS_NUM"                  VARCHAR2 (2) NOT NULL ENABLE,
"NUM_INS_NUM_NAME"             NVARCHAR2(100),
    CONSTRAINT "CMDS_M_NUM_INS_NUM_PK" PRIMARY KEY ("NUM_INS_NUM") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
