CREATE TABLE "CMDS_M_SSPCT_DSS_SELECT"
(
"SSPCT_DSS_SELECT_DIV"         NUMBER (1) NOT NULL ENABLE,
"SSPCT_DSS_SELECT_DIV_NAME"    NVARCHAR2(20),
    CONSTRAINT "CMDS_M_SSPCT_DSS_SELECT_PK" PRIMARY KEY ("SSPCT_DSS_SELECT_DIV") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
