CREATE TABLE "CMDS_M_MAIN_SKWD_SELECT"
(
"MAIN_SKWD_SELECT_DIV"         NUMBER (1) NOT NULL ENABLE,
"MAIN_SKWD_SELECT_DIV_NAME"    NVARCHAR2(20),
    CONSTRAINT "CMDS_M_MAIN_SKWD_SELECT_PK" PRIMARY KEY ("MAIN_SKWD_SELECT_DIV") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
