CREATE TABLE "CMDS_M_PHA_CLS"
(
"PHA_CLS"                      VARCHAR2 (3) NOT NULL ENABLE,
"PHA_CLS_NAME"                 NVARCHAR2(50),
    CONSTRAINT "CMDS_M_PHA_CLS_PK" PRIMARY KEY ("PHA_CLS") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
