CREATE TABLE "CMDS_M_GENERIC"
(
"GENERIC"                      VARCHAR2 (1) NOT NULL ENABLE,
"GENERIC_NAME"                 NVARCHAR2(10),
    CONSTRAINT "CMDS_M_GENERIC_PK" PRIMARY KEY ("GENERIC") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
