CREATE TABLE "CMDS_M_AGE_LOAD"
(
"AGE_LOAD_DIV"                 VARCHAR2 (1) NOT NULL ENABLE,
"AGE_LOAD_DIV_NAME"            NVARCHAR2(10),
    CONSTRAINT "CMDS_M_AGE_LOAD_PK" PRIMARY KEY ("AGE_LOAD_DIV") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
