CREATE TABLE "CMDS_M_ICHITAIRO_DIV"
(
"ICHITAIRO"                    VARCHAR2 (1) NOT NULL ENABLE,
"ICHITAIRO_NAME"               NVARCHAR2(10),
    CONSTRAINT "CMDS_M_ICHITAIRO_DIV_PK" PRIMARY KEY ("ICHITAIRO") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
