CREATE TABLE "CMDS_M_ORI_SND_DIV"
(
"ORI_SND_DIV"                  NUMBER   (1,0) NOT NULL ENABLE,
"ORI_SND_DIV_NAME"             NVARCHAR2(10),
    CONSTRAINT "CMDS_M_ORI_SND_DIV_PK" PRIMARY KEY ("ORI_SND_DIV") USING INDEX
        TABLESPACE NDB_USERS1
)
TABLESPACE NDB_USERS1
NOLOGGING
PARALLEL 96
;
